### ISSUE TITLE
部署失败，无法部署到腾讯云

### ISSUE THREAD

**Issue by guduuyyfy** [chen310/NeteaseCloudMusicTasks#1]
25l正在初始化... Action: "deploy" - Stage: "dev" - App: "NeteaseCloudMusicTasks" - Name: "NeteaseCloudMusicTasks" 准备中... 上传中... 部署中...   RequestError: Error: connect ETIMEDOUT 49.51.42.237:443 at new RequestError (/usr/local/lib/node_modules/serverless/node_modules/request-promise-core/lib/errors.js:14:15) at Request.plumbing.callback (/usr/local/lib/node_modules/serverless/node_modules/request-promise-core/lib/plumbing.js:87:29) at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/serverless/node_modules/request-promise-core/lib/plumbing.js:46:31) at self.callback (/usr/local/lib/node_modules/serverless/node_modules/request/request.js:185:22) at Request.emit (node:events:390:28) at Request.onRequestError (/usr/local/lib/node_modules/serverless/node_modules/request/request.js:877:8) at ClientRequest.emit (node:events:390:28) at TLSSocket.socketErrorListener (node:_http_client:447:9) at TLSSocket.emit (node:events:390:28) at emitErrorNT (node:internal/streams/destroy:157:8)  185s › NeteaseCloudMusicTasks › Error: connect ETIMEDOUT 49.51.42.237:443 帮助文档: https://www.serverless.com/cn/framework/docs/ BUG提交: https://github.com/serverless/serverless-tencent/issues 问答社区: https://github.com/serverless/serverless-tencent/discussions  25h
部署失败 
Error: Process completed with exit code 1.

**Comment by chen310** [comment]
> 25l正在初始化... Action: "deploy" - Stage: "dev" - App: "NeteaseCloudMusicTasks" - Name: "NeteaseCloudMusicTasks" 准备中... 上传中... 部署中... RequestError: Error: connect ETIMEDOUT 49.51.42.237:443 at new RequestError (/usr/local/lib/node_modules/serverless/node_modules/request-promise-core/lib/errors.js:14:15) at Request.plumbing.callback (/usr/local/lib/node_modules/serverless/node_modules/request-promise-core/lib/plumbing.js:87:29) at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/serverless/node_modules/request-promise-core/lib/plumbing.js:46:31) at self.callback (/usr/local/lib/node_modules/serverless/node_modules/request/request.js:185:22) at Request.emit (node:events:390:28) at Request.onRequestError (/usr/local/lib/node_modules/serverless/node_modules/request/request.js:877:8) at ClientRequest.emit (node:events:390:28) at TLSSocket.socketErrorListener (node:_http_client:447:9) at TLSSocket.emit (node:events:390:28) at emitErrorNT (node:internal/streams/destroy:157:8) 185s › NeteaseCloudMusicTasks › Error: connect ETIMEDOUT 49.51.42.237:443 帮助文档: https://www.serverless.com/cn/framework/docs/ BUG提交: https://github.com/serverless/serverless-tencent/issues 问答社区: https://github.com/serverless/serverless-tencent/discussions 25h 部署失败 Error: Process completed with exit code 1.

重新部署也不行吗？对这个错误我也不是很清楚

**Comment by guduuyyfy** [comment]
> 重新部署也不行吗？对这个错误我也不是很清楚

自己解决了 发现是腾讯云密钥的问题  主账户只能用一个密钥
