### ISSUE TITLE
大佬我GitHub显示部署成功了为什么提示环境变量不存在

### ISSUE THREAD

**Issue by ghost** [chen310/NeteaseCloudMusicTasks#101]
环境变量 TENCENT_SECRET_ID 或 TENCENT_SECRET_KEY 不存在。项目地址: https://github.com/chen310/NeteaseCloudMusicTasks

环境变量保存失败

Response RequestId:d777f283-f737-4e26-b9ab-533056eb09ae RetMsg:null

END RequestId:d777f283-f737-4e26-b9ab-533056eb09ae

Report RequestId:d777f283-f737-4e26-b9ab-533056eb09ae Duration:14580ms Memory:64MB MemUsage:37.639923MB

**Comment by chen310** [comment]
你是自己上传代码部署的吧。没事，也能用
