### ISSUE TITLE
telegram推送问题

### ISSUE THREAD

**Issue by panliang-rm** [chen310/NeteaseCloudMusicTasks#102]
![image](https://user-images.githubusercontent.com/54338815/158107311-48ca2ffa-62e2-4ba4-9db2-91a73ceaf972.png)
![image](https://user-images.githubusercontent.com/54338815/158107316-afcf8c7a-8e10-408b-b2c8-9a1231a3d1a3.png)

**Comment by DrKoschei** [comment]
same

**Comment by L-4455** [comment]
telegram推送好像不能用的

**Comment by pat28229** [comment]
我的也是调用失败，似乎是网络问题，会不会是因为地区的原因，试试改到境外

**Comment by pat28229** [comment]
我成功了，默认是配置到广州，改成香港就好啦

**Comment by panliang-rm** [comment]
> 我成功了，默认是配置到广州，改成香港就好啦

修改到其它城市不会有别的问题吗？我之前想的也是服务器是国内的问题

**Comment by mybdye** [comment]
> > 我成功了，默认是配置到广州，改成香港就好啦
> 
> 修改到其它城市不会有别的问题吗？我之前想的也是服务器是国内的问题

1. `REGION` >> `ap-hongkong` 然后`X-Real-IP` 里填写国内 IP
2. 自建cf tg 反代，替换 telegram.py 的 api 域名
@chen310  建议加个自定义反代？

**Comment by chen310** [comment]
@mybdye 

在配置文件中增加tg自定义域名？

**Comment by mybdye** [comment]
> 

是的

**Comment by chen310** [comment]
@mybdye 已更新
