### ISSUE TITLE
大佬在Github部署成功以后在哪里编辑文件

### ISSUE THREAD

**Issue by Mriccou** [chen310/NeteaseCloudMusicTasks#103]
部署成功了但是不知道在哪里编辑config.example.json

**Comment by chen310** [comment]
https://console.cloud.tencent.com/scf/list
找到刚刚部署成功的云函数，点进去。编辑 config.json 文件

**Comment by Mriccou** [comment]
云函数需要填写环境变量吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chen310/NeteaseCloudMusicTasks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月14日(星期一) 下午2:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chen310/NeteaseCloudMusicTasks] 大佬在Github部署成功以后在哪里编辑文件 (Issue #103)





 
https://console.cloud.tencent.com/scf/list
 找到刚刚部署成功的云函数，点进去。编辑 config.json 文件
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chen310** [comment]
不需要你手动填
