### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by 13063516125** [chen310/NeteaseCloudMusicTasks#105]
START RequestId: ef6b658d-e9e4-433c-995e-3fb341267cdc

Init Report RequestId: ef6b658d-e9e4-433c-995e-3fb341267cdc Coldstart: 964ms (PullCode: 80ms InitRuntime: 6ms InitFunction: 878ms) Memory: 128MB MemUsage: 24.11MB

Version: 2.19

Starting new HTTPS connection (1): music.163.com:443

https://music.163.com:443 "POST /weapi/user/level HTTP/1.1" 200 52

https://music.163.com:443 "POST /weapi/login/cellphone HTTP/1.1" 200 439

**用户信息**

  登录失败，{'code': -462, 'data': {'actionCode': '1076401', 'verifyType': 40, 'verifyId': 1007602, 'verifyUrl': 'https://st.music.163.com/encrypt-pages', 'blockText': '验证成功后，可进行下一步操作哦~', 'verifyToken': '00.40.c7fc33925bd09e5c44913205234edf0f.2104577203', 'btnText': '', 'orpheusUrl': '', 'frontRuleIds': [1076401], 'params': {'event_id': '00211457778786631716', 'sign': 'e2f6d71efb8b2549d97813bf74311831'}, 'url': 'https://st.music.163.com/encrypt-pages?params=%7B%22sign%22%3A%22e2f6d71efb8b2549d97813bf74311831%22%2C%22event_id%22%3A%2200211457778786631716%22%7D&verifyType=40&verifyId=1007602&verifyToken=00.40.c7fc33925bd09e5c44913205234edf0f.2104577203&actionCode=1076401'}, 'message': None}

Starting new HTTPS connection (1): sctapi.ftqq.com:443

https://sctapi.ftqq.com:443 "POST /SCT114831Tx3jYskoZzEZ73DWUCNf0cvqJ.send HTTP/1.1" 400 267

Response RequestId:ef6b658d-e9e4-433c-995e-3fb341267cdc RetMsg:null

END RequestId:ef6b658d-e9e4-433c-995e-3fb341267cdc

Report RequestId:ef6b658d-e9e4-433c-995e-3fb341267cdc Duration:554ms Memory:128MB MemUsage:38.800781MB

**Comment by 13063516125** [comment]
未开启登录保护

**Comment by chen310** [comment]
没遇过这种情况

**Comment by chen310** [comment]
换ip试过吗

**Comment by 13063516125** [comment]
一个账号有无IP都登录失败，另一个现在又可以登录了

**Comment by bookaxiba** [comment]
我也是这样，昨天还能正常用来着

**Comment by Mercury-hhn** [comment]
云函数 换ip还是不好用 显示需要认证

**Comment by chen310** [comment]
请暂时用cookie登录，使用方法：
在云函数的函数管理中添加环境变量。首先在网页登录网易云账号，然后获取cookie，可以只复制MUSIC_U部分。
假如手机号为 18888888888 ，则环境变量的 key 填写 `COOKIE_18888888888 ` ， value 填写 `MUSIC_U:xxxxxxxxxxxxxxxx;`
如果使用邮箱登录，请将非数字和字母部分替换成下划线`_`，即如果邮箱为 123_abc@abc.com
则key填写 COOKIE_123_abc_abc.com

**Comment by acanyun** [comment]
问题同上，登陆失败

**Comment by Ele-sorriu** [comment]
获取cookie如下  MUSIC_U在值的最后面
![image](https://user-images.githubusercontent.com/76163920/158494600-2297fcd9-8ae3-4f3c-bdac-c085d38491fe.png)
然后添加环境变量在函数管理界面
![image](https://user-images.githubusercontent.com/76163920/158494713-a00b5b61-cb7f-4599-b2fc-fe9952d1ffbd.png)
编辑添加
![image](https://user-images.githubusercontent.com/76163920/158494866-f6c25e5d-2246-4895-9b2b-c17150e6293c.png)
重新测试成功

日志:
START RequestId: efa3b343-6bda-427b-819a-dc4470eddf5d
Init Report RequestId: efa3b343-6bda-427b-819a-dc4470eddf5d Coldstart: 934ms (PullCode: 123ms InitRuntime: 13ms InitFunction: 798ms) Memory: 128MB MemUsage: 25.25MB
Version: 2.19
Starting new HTTPS connection (1): music.163.com:443
https://music.163.com:443 "POST /weapi/user/level HTTP/1.1" 200 197
已通过 cookie 登录

**Comment by bug1615** [comment]
> 获取cookie如下 MUSIC_U在值的最后面 ![image](https://user-images.githubusercontent.com/76163920/158494991-9593e3db-9823-43f8-9001-4be2ed2eb318.png)
> 
> 然后添加环境变量在函数管理界面 ![image](https://user-images.githubusercontent.com/76163920/158494713-a00b5b61-cb7f-4599-b2fc-fe9952d1ffbd.png)
> 
> 编辑添加 ![image](https://user-images.githubusercontent.com/76163920/158494866-f6c25e5d-2246-4895-9b2b-c17150e6293c.png)
> 
> 重新测试成功
> 
> 日志: START RequestId: efa3b343-6bda-427b-819a-dc4470eddf5d Init Report RequestId: efa3b343-6bda-427b-819a-dc4470eddf5d Coldstart: 934ms (PullCode: 123ms InitRuntime: 13ms InitFunction: 798ms) Memory: 128MB MemUsage: 25.25MB Version: 2.19 Starting new HTTPS connection (1): music.163.com:443 https://music.163.com:443 "POST /weapi/user/level HTTP/1.1" 200 197 已通过 cookie 登录

成功了，多谢图片教程

**Comment by bookaxiba** [comment]
cookie登录成功

**Comment by dissl** [comment]
就成功了一次后面又不成功了

**Comment by 222119359** [comment]
我是添加了变量还是这样子

**Comment by capitalwell** [comment]
同样，更新完后添加 cookie secret 依然不能登录，需要验证，未开启登录保护。
日志如下:
`START RequestId:d1c7142a-afed-4fa8-84c3-4440c9df4ae6

Version: 2.19

Starting new HTTPS connection (1): music.163.com:443

https://music.163.com:443 "POST /weapi/user/level HTTP/1.1" 200 52

https://music.163.com:443 "POST /weapi/login/cellphone HTTP/1.1" 200 438

**用户信息**


  登录失败，{'code': -462, 'data': {'actionCode': '1076401', 'verifyType': 40, 'verifyId': 1007602, 'verifyUrl': 'https://st.music.163.com/encrypt-pages', 'blockText': '验证成功后，可进行下一步操作哦~', 'verifyToken': '00.40.85880959af713d583a1326c568447aee.3523339175', 'btnText': '', 'orpheusUrl': '', 'frontRuleIds': [1076401], 'params': {'event_id': '00212120400964190232', 'sign': 'b4077b0a5303e55e187c32ab7cb30da7'}, 'url': 'https://st.music.163.com/encrypt-pages?params=%7B%22sign%22%3A%22b4077b0a5303e55e187c32ab7cb30da7%22%2C%22event_id%22%3A%2200212120400964190232%22%7D&verifyType=40&verifyId=1007602&verifyToken=00.40.85880959af713d583a1326c568447aee.3523339175&actionCode=1076401'}, 'message': None}


Starting new HTTPS connection (1): sctapi.ftqq.com:443

https://sctapi.ftqq.com:443 "POST /SCT109642TInaLrvEu0TmsNNPHMotjBttB.send HTTP/1.1" 400 267

Response RequestId:d1c7142a-afed-4fa8-84c3-4440c9df4ae6 RetMsg:null

END RequestId:d1c7142a-afed-4fa8-84c3-4440c9df4ae6

Report RequestId:d1c7142a-afed-4fa8-84c3-4440c9df4ae6 Duration:411ms Memory:128MB MemUsage:23.718750MB`

**Comment by FishEyeiii** [comment]
同上，添加了变量还是显示需要认证

**Comment by q1780011081** [comment]
还是一样没用

**Comment by chen310** [comment]
更新了代码，可以直接在配置文件中填写cookie https://github.com/chen310/NeteaseCloudMusicTasks#%E8%B4%A6%E5%8F%B7%E5%AF%86%E7%A0%81

**Comment by 222119359** [comment]
> 更新了代码，可以直接在配置文件中刷新cookie https://github.com/chen310/NeteaseCloudMusicTasks#%E8%B4%A6%E5%8F%B7%E5%AF%86%E7%A0%81

感谢！更新后在配置文件加的 CK能够登录了

**Comment by chen310** [comment]
暂时解决，更新代码后应该就能用账号密码登录了
