### ISSUE TITLE
音乐人动态发布的云豆当次领取提示未完成，当天需要再运行一次来领取

### ISSUE THREAD

**Issue by YohoYang** [chen310/NeteaseCloudMusicTasks#106]
腾讯云部署，实际任务是完成的，打开界面和再次运行都可以成功领取，可能是网易云那边刷新有延迟，可以尝试加一下延迟，辛苦大佬！

![Snipaste_2022-03-15_03-02-55](https://user-images.githubusercontent.com/16574473/158242993-e7c3e5be-1678-41ef-a38d-7948c9859c19.png)

**Comment by chen310** [comment]
如果是延迟的话。那就不用管了，因为第二天总会领取的

**Comment by YohoYang** [comment]
> 如果是延迟的话。那就不用管了，因为第二天总会领取的

理论上来说是这样，但是网易改版后显示这个豆没领当天会过期- -

![image](https://user-images.githubusercontent.com/16574473/158297019-c1be4440-2654-446e-9216-ef17a263891a.png)

**Comment by chen310** [comment]
设置一天运行两次吧，因为不知道延迟到底有多大

**Comment by YohoYang** [comment]
> 设置一天运行两次吧，因为不知道延迟到底有多大

OK，现在就是一天跑两次了
