### ISSUE TITLE
青龙拉代码报错

### ISSUE THREAD

**Issue by woshiliuxu** [chen310/NeteaseCloudMusicTasks#107]
![Uploading image.png…]()

**Comment by woshiliuxu** [comment]
`root@qinglong:/ql $ ql repo https://github.com/chen310/NeteaseCloudMusicTasks.git "index.py" "" "py"`
`请先登录！`

**Comment by chen310** [comment]
要先在网页上登录青龙的吧

**Comment by woshiliuxu** [comment]
> 要先在网页上登录青龙的吧

登录了的

**Comment by chen310** [comment]
看看这个对你有没有帮助 https://github.com/whyour/qinglong/issues/129

**Comment by woshiliuxu** [comment]
> 
我用面板把代码拉下来了
