### ISSUE TITLE
云圈任务报错，参数错误

### ISSUE THREAD

**Issue by FlechazoPh** [chen310/NeteaseCloudMusicTasks#108]
日志：
<img width="502" alt="image" src="https://user-images.githubusercontent.com/94276146/158331054-bb8a4b23-0fa4-4f32-a86b-418f128c66e8.png">

配置：
<img width="534" alt="image" src="https://user-images.githubusercontent.com/94276146/158331179-268e535c-ca1c-4bae-8d9e-f7a065b99bb5.png">

**Comment by chen310** [comment]
ID 填错了。可以直接不填，如果不填还报错的话就到云圈页面右上角分享，链接里 circleId= 后面的字符就是 ID
