### ISSUE TITLE
登入失败

### ISSUE THREAD

**Issue by matocool** [chen310/NeteaseCloudMusicTasks#112]
START RequestId: a26beb48-4c5a-4d47-815c-d1c3c01eba88

Init Report RequestId: a26beb48-4c5a-4d47-815c-d1c3c01eba88 Coldstart: 1588ms (PullCode: 311ms InitRuntime: 48ms InitFunction: 1229ms) Memory: 128MB MemUsage: 24.92MB

### 用户1

Starting new HTTPS connection (1): music.163.com:443

https://music.163.com:443 "POST /weapi/user/level HTTP/1.1" 200 52

https://music.163.com:443 "POST /weapi/login/cellphone HTTP/1.1" 200 432

#### 用户信息

- 登录失败，{'code': -462, 'data': {'actionCode': '1076401', 'verifyType': 40, 'verifyId': 1007602, 'verifyUrl': 'https://st.music.163.com/encrypt-pages', 'blockText': '验证成功后，可进行下一步操作哦~', 'verifyToken': '00.40.7d640b145fbcb3d10d0f9745d0665029.496901162', 'btnText': '', 'orpheusUrl': '', 'frontRuleIds': [1076401], 'params': {'event_id': '00211915374966480909', 'sign': '8816f1be2e3164b849d98a171cfd754f'}, 'url': 'https://st.music.163.com/encrypt-pages?params=%7B%22sign%22%3A%228816f1be2e3164b849d98a171cfd754f%22%2C%22event_id%22%3A%2200211915374966480909%22%7D&verifyType=40&verifyId=1007602&verifyToken=00.40.7d640b145fbcb3d10d0f9745d0665029.496901162&actionCode=1076401'}, 'message': None}

Starting new HTTPS connection (1): sctapi.ftqq.com:443

https://sctapi.ftqq.com:443 "POST /SCT41834TQRwB5QM41wfIevEX5Tj0w3fO.send HTTP/1.1" 200 108

Response RequestId:a26beb48-4c5a-4d47-815c-d1c3c01eba88 RetMsg:null

END RequestId:a26beb48-4c5a-4d47-815c-d1c3c01eba88

Report RequestId:a26beb48-4c5a-4d47-815c-d1c3c01eba88 Duration:718ms Memory:128MB MemUsage:36.222656MB

--------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------

然后按下面方式登入

请暂时用cookie登录，使用方法：
在云函数的管理中添加环境变量。首先在网页登录网易云账号，然后获取cookie，只需复制MUSIC_U部分。如果
手机号为18888888888，则可以重新填写环境的键COOKIE_18888888888 ，值填写MUSIC_U:xxxxxxxxxxxxxxxx;
如果使用邮箱，非数字邮箱和部分替换成下划线_，即如果邮箱为[123_abc@abc.comkey](mailto:123_abc@abc.com)
则COOKIE_123_abc_abc_com

--------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------

START RequestId: c2c4d33d-cba7-4d4d-90d6-e0342e55bc81

Init Report RequestId: c2c4d33d-cba7-4d4d-90d6-e0342e55bc81 Coldstart: 919ms (PullCode: 82ms InitRuntime: 5ms InitFunction: 832ms) Memory: 128MB MemUsage: 24.83MB

#### 用户信息

- 登录失败，请填写账号密码

Starting new HTTPS connection (1): sctapi.ftqq.com:443

https://sctapi.ftqq.com:443 "POST /SCT41834TQRwB5QM41wfIevEX5Tj0w3fO.send HTTP/1.1" 200 108

Response RequestId:c2c4d33d-cba7-4d4d-90d6-e0342e55bc81 RetMsg:null

END RequestId:c2c4d33d-cba7-4d4d-90d6-e0342e55bc81

Report RequestId:c2c4d33d-cba7-4d4d-90d6-e0342e55bc81 Duration:2445ms Memory:128MB MemUsage:36.609375MB

--------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------

但是填写手机 以及密码    而且我把IP也换了        依然提示如下

START RequestId: 688b33d2-a4f7-4e33-b42f-f6290a6f6b9a

Init Report RequestId: 688b33d2-a4f7-4e33-b42f-f6290a6f6b9a Coldstart: 952ms (PullCode: 75ms InitRuntime: 5ms InitFunction: 872ms) Memory: 128MB MemUsage: 24.76MB

### 用户1

Starting new HTTPS connection (1): music.163.com:443

https://music.163.com:443 "POST /weapi/user/level HTTP/1.1" 200 52

https://music.163.com:443 "POST /weapi/login/cellphone HTTP/1.1" 200 437

#### 用户信息

- 登录失败，{'code': -462, 'data': {'actionCode': '1076401', 'verifyType': 40, 'verifyId': 1007602, 'verifyUrl': 'https://st.music.163.com/encrypt-pages', 'blockText': '验证成功后，可进行下一步操作哦

**Comment by Silentely** [comment]
同。我这边也报错了
`【用户信息】
  ➢ 登录失败，{'code': -462, 'data': {'actionCode': '1076401', 'verifyType': 40, 'verifyId': 1007602, 'verifyUrl': 'https://st.music.163.com/encrypt-pages', 'blockText': '验证成功后，可进行下一步操作哦~', 'verifyToken': '00`

**Comment by chen310** [comment]
@matocool 更新一下代码

**Comment by bug1615** [comment]
> @matocool 更新一下代码

大佬，更新了代码依旧报错
START RequestId: 026df1d8-9003-4122-a952-b8da08658c52

```
Init Report RequestId: 026df1d8-9003-4122-a952-b8da08658c52 Coldstart: 1003ms (PullCode: 221ms InitRuntime: 5ms InitFunction: 777ms) Memory: 128MB MemUsage: 24.87MB

Version: 2.19

Starting new HTTPS connection (1): music.163.com:443

https://music.163.com:443 "POST /weapi/user/level HTTP/1.1" 200 52

https://music.163.com:443 "POST /weapi/login/cellphone HTTP/1.1" 200 438

**用户信息**


  登录失败，{'code': -462, 'data': {'actionCode': '1076401', 'verifyType': 40, 'verifyId': 1007602, 'verifyUrl': 'https://st.music.163.com/encrypt-pages', 'blockText': '验证成功后，可进行下一步操作哦~', 'verifyToken': '00.40.88e1e3e6093c7e73df2a751911cc6972.1185374427', 'btnText': '', 'orpheusUrl': '', 'frontRuleIds': [1076401], 'params': {'event_id': '00212006087548948487', 'sign': 'a6b20fe3fd30e422c93e08fc7c98b7a7'}, 'url': 'https://st.music.163.com/encrypt-pages?params=%7B%22sign%22%3A%22a6b20fe3fd30e422c93e08fc7c98b7a7%22%2C%22event_id%22%3A%2200212006087548948487%22%7D&verifyType=40&verifyId=1007602&verifyToken=00.40.88e1e3e6093c7e73df2a751911cc6972.1185374427&actionCode=1076401'}, 'message': None}


Response RequestId:026df1d8-9003-4122-a952-b8da08658c52 RetMsg:null

END RequestId:026df1d8-9003-4122-a952-b8da08658c52

Report RequestId:026df1d8-9003-4122-a952-b8da08658c52 Duration:186ms Memory:128MB MemUsage:36.609375MB
```

**Comment by chen310** [comment]
更新完后，设置cookie

**Comment by bug1615** [comment]
> 更新完后，设置cookie

可以了，谢谢大佬
