### ISSUE TITLE
tg push status_code:400

### ISSUE THREAD

**Issue by mybdye** [chen310/NeteaseCloudMusicTasks#114]
<img width="787" alt="截屏2022-03-16 11 05 09" src="https://user-images.githubusercontent.com/21116709/158508722-91fcd70c-af79-4b1e-9df9-adab2f22310f.png">

/src/push/Telegram.py

`'parse_mode': "MarkdownV2"`
改成
`'parse_mode': "Markdown"`

<img width="1006" alt="截屏2022-03-16 10 56 46" src="https://user-images.githubusercontent.com/21116709/158507721-1424ca6f-5248-429a-bf80-f85e4852a7ac.png">

<img width="234" alt="截屏2022-03-16 10 54 03" src="https://user-images.githubusercontent.com/21116709/158507459-aef6d18d-52c9-4438-a510-babf13a3f618.png">

**Comment by chen310** [comment]
改成 Markdown 后，推送的样式是什么样的？

**Comment by mybdye** [comment]
> 改成 Markdown 后，推送的样式是什么样的？

默认的 `mdmsg_compat` 如下图， `mdmsg` `textmsg` 也基本类似，多些符号。
![IMG_8298](https://user-images.githubusercontent.com/21116709/158554543-3e70be39-62d6-4917-860a-275fa0df069c.PNG)
