### ISSUE TITLE
更新完添加 cookie secret 后仍不能登录，需要验证，未开启登录保护。

### ISSUE THREAD

**Issue by matocool** [chen310/NeteaseCloudMusicTasks#115]
时间：2022-03-16 17:56:25运行时间:648ms运行内存:39.82908630371094MB
日志:

START RequestId:d08ecb76-e7fd-48f4-952c-547e846a3070

Version: 2.19

Starting new HTTPS connection (1): music.163.com:443

https://music.163.com:443 "POST /weapi/user/level HTTP/1.1" 200 52

https://music.163.com:443 "POST /weapi/login/cellphone HTTP/1.1" 200 438

**用户信息**

登录失败，{'code': -462, 'data': {'actionCode': '1076401', 'verifyType': 40, 'verifyId': 1007602, 'verifyUrl': 'https://st.music.163.com/encrypt-pages', 'blockText': '验证成功后，可进行下一步操作哦~', 'verifyToken': '00.40.a119e29d529d14ce399d652cbb83ce3a.1932459198', 'btnText': '', 'orpheusUrl': '', 'frontRuleIds': [1076401], 'params': {'event_id': '00212144949088813081', 'sign': 'a3806720123438581f9d17a9df308ce1'}, 'url': 'https://st.music.163.com/encrypt-pages?params=%7B%22sign%22%3A%22a3806720123438581f9d17a9df308ce1%22%2C%22event_id%22%3A%2200212144949088813081%22%7D&verifyType=40&verifyId=1007602&verifyToken=00.40.a119e29d529d14ce399d652cbb83ce3a.1932459198&actionCode=1076401'}, 'message': None}

Starting new HTTPS connection (1): sctapi.ftqq.com:443

https://sctapi.ftqq.com:443 "POST /SCT41834TQRwB5QM41wfIevEX5Tj0w3fO.send HTTP/1.1" 400 267

Response RequestId:d08ecb76-e7fd-48f4-952c-547e846a3070 RetMsg:null

END RequestId:d08ecb76-e7fd-48f4-952c-547e846a3070

Report RequestId:d08ecb76-e7fd-48f4-952c-547e846a3070 Duration:648ms Memory:128MB MemUsage:39.829086MB

+-++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

已按照教程说明更新至version": "2.19",

同时按照要求在环境变量	填入以下数据
COOKIE_13000000000
 MUSIC_U=xxxxxxxxxxxxx;     （这里的；我都是填上了）

同时参考该帖子校对了一次，，流程上肯定是没错的 全部按照要求来

https://github.com/chen310/NeteaseCloudMusicTasks/issues/105      

但是该帖子最后的几个网友一样也是同病相怜  请求作者大大看看 谢谢

**Comment by MavisTok** [comment]
![image](https://user-images.githubusercontent.com/52002734/158573095-1eaa0e29-815e-4acd-a81b-f8bd291c853c.png)
我也是同样的问题

**Comment by chen310** [comment]
目前还没有解决办法

**Comment by MavisTok** [comment]
> 目前还没有解决办法

等待解决方案🥰

**Comment by bookaxiba** [comment]
环境变量那里是      MUSIC_U：      不是MUSIC_U=，然后看看自己有没有多复制空格之类的

**Comment by matocool** [comment]
> MUSIC_U：

我试试 谢谢

**Comment by matocool** [comment]
> 环境变量那里是 MUSIC_U： 不是MUSIC_U=，然后看看自己有没有多复制空格之类的

谢谢 大佬 搞定了！！！！

**Comment by q1780011081** [comment]
> 目前还没有解决办法



> 环境变量那里是 MUSIC_U： 不是MUSIC_U=，然后看看自己有没有多复制空格之类的

为啥我还是不可以！

**Comment by q1780011081** [comment]
> 环境变量那里是 MUSIC_U： 不是MUSIC_U=，然后看看自己有没有多复制空格之类的

MUSIC_U：XXXXXXXXXXX;

是这样吗

**Comment by chen310** [comment]
> 

英文冒号，不是中文的

**Comment by q1780011081** [comment]
> > 
> 
> 英文冒号，不是中文的

好啦！！！！！！谢谢！！！！！

**Comment by matocool** [comment]
> > > 
> > 
> > 
> > 英文冒号，不是中文的
> 
> 好啦！！！！！！谢谢！！！！！

哥们也成功了吗

**Comment by chen310** [comment]
更新了代码，可以直接在配置文件中填写cookie https://github.com/chen310/NeteaseCloudMusicTasks#%E8%B4%A6%E5%8F%B7%E5%AF%86%E7%A0%81
