### ISSUE TITLE
感谢好大哥：bookaxiba   指点。。cookie方式登入不了的可以进来看下先。

### ISSUE THREAD

**Issue by matocool** [chen310/NeteaseCloudMusicTasks#116]
https://github.com/chen310/NeteaseCloudMusicTasks/issues/115   我发的原贴，好大哥：bookaxiba   指点出了我的错误地方。

环境变量那里是 MUSIC_U： 不是MUSIC_U=，然后看看自己有没有多复制空格之类的 

然后MUSIC_U=  xxxxx ;        (;)这个符号我是加入进去了。大家看看有没有漏打这个符号

然后大家测试下，

**Comment by matocool** [comment]
我这边测试了2次 都成功了！！！

**Comment by q1780011081** [comment]
为啥我还是没用！

**Comment by q1780011081** [comment]
> 我测试了2次 都成功了！！！

可以给个具体的例子莫

**Comment by chen310** [comment]
> cookie可以维持多久哇

应该不会很短

**Comment by imzql** [comment]
![576fad0c6831981871034953d7de74f.png](https://api.usj.cc/ota/2022/03/17/IchqCvoQ.png)
小白问个问题，为什么我这样设置还是一直报错登陆不上呢

**Comment by zhao19980201** [comment]
不是在这弄 ...



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月17日(星期四) 下午2:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chen310/NeteaseCloudMusicTasks] 感谢好大哥：bookaxiba   指点。。cookie方式登入不了的可以进来看下先。 (Issue #116)





 

 小白问个问题，为什么我这样设置还是一直报错登陆不上呢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chen310** [comment]
> ![576fad0c6831981871034953d7de74f.png](https://api.usj.cc/ota/2022/03/17/IchqCvoQ.png)
> 小白问个问题，为什么我这样设置还是一直报错登陆不上呢

多了空格

**Comment by imzql** [comment]
![a2eddf093d984e9e3c77c732c48b442.png](https://api.usj.cc/ota/2022/03/17/Q1DJsyBU.png)
还是报这个错误，删了之后

**Comment by chen310** [comment]
> ![a2eddf093d984e9e3c77c732c48b442.png](https://api.usj.cc/ota/2022/03/17/Q1DJsyBU.png)
> 还是报这个错误，删了之后

你没更新代码

**Comment by imzql** [comment]
> > ![a2eddf093d984e9e3c77c732c48b442.png](https://camo.githubusercontent.com/d70498505023282f461fecd161919d5c474bfc74e4eba7f24c041aa5af9d88e6/68747470733a2f2f6170692e75736a2e63632f6f74612f323032322f30332f31372f5131444a737942552e706e67)
> > 还是报这个错误，删了之后
> 
> 你没更新代码

谢谢大佬，解决了
