### ISSUE TITLE
大佬我github部署成功了以后云函数里面不会自动部署代码是为什么

### ISSUE THREAD

**Issue by Mriccou** [chen310/NeteaseCloudMusicTasks#121]
我绑定了层以后又重新部署了一下为什么还是不会自动部署代码需要自己手动上传

![image](https://user-images.githubusercontent.com/101546131/158738935-3c655466-be92-4490-9da1-fe470259e754.png)

![image](https://user-images.githubusercontent.com/101546131/158738951-8909bda8-f211-4953-95b3-9e583ab8cc28.png)

**Comment by chen310** [comment]
地域选对了吗，默认是广州

**Comment by Mriccou** [comment]
我地区就是默认的这个需要更改到其他地域吗

**Comment by chen310** [comment]
https://console.cloud.tencent.com/scf/list 截图看看

**Comment by Mriccou** [comment]
大佬部署问题解决了，但是填写完了配置是报错的

START RequestId: d235a68e-c597-4ae9-ad06-1fa0b82adc11

Init Report RequestId: d235a68e-c597-4ae9-ad06-1fa0b82adc11 Coldstart: 551ms (PullCode: 89ms InitRuntime: 4ms InitFunction: 458ms) Memory: 128MB MemUsage: 16.10MB

ERROR RequestId: d235a68e-c597-4ae9-ad06-1fa0b82adc11 Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/index.py", line 6, in <module>     import json5 ModuleNotFoundError: No module named 'json5'", "statusCode": 443}

END RequestId: d235a68e-c597-4ae9-ad06-1fa0b82adc11

Report RequestId: d235a68e-c597-4ae9-ad06-1fa0b82adc11 Duration: 0ms Memory: 128MB MemUsage: 16.10MB

START RequestId:d235a68e-c597-4ae9-ad06-1fa0b82adc11

ERROR RequestId:d235a68e-c597-4ae9-ad06-1fa0b82adc11 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 6, in \u003cmodule\u003e\n    import json5\nModuleNotFoundError: No module named 'json5'","statusCode":443}

END RequestId:d235a68e-c597-4ae9-ad06-1fa0b82adc11

Report RequestId:d235a68e-c597-4ae9-ad06-1fa0b82adc11 Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by chen310** [comment]
请仔细看文档，你这是没有绑定层
