### ISSUE TITLE
感觉重复率好高哦~~~

### ISSUE THREAD

**Issue by matocool** [chen310/NeteaseCloudMusicTasks#127]
网易云音乐今天听歌18首，累计听歌106028首
🥺 您是免费用户或订阅会员已过期，需要进入详情页面才能查看内容。
 订阅支持请点这里 → sct.ftqq.com/donate
 额度：2/5
--------------------------------------------------------------------------------------------
当听歌数量达到一定的时候，感觉每日成功刷的数量明显变少很多。
不知道能不能换个思路？在刷歌单的同时刷刷私人FM之类的？？

**Comment by chen310** [comment]
都已经10万首了，我觉得应该没有多大必要再刷了吧。听歌越多重复自然是会越高的。

**Comment by matocool** [comment]
> 按道理讲，私人FM不会重复的歌曲更多吗

貌似不会，其实我这是想变相统计网易云到底大概有多少音乐。。。。时间线拉长 数据更有意义

**Comment by chen310** [comment]
你这么一说的话，其实可以先记下哪些ID是有效的，然后从头开始遍历，每天取出300个

**Comment by chen310** [comment]
暂时就这样吧，不做修改
