### ISSUE TITLE
云函数测试失败

### ISSUE THREAD

**Issue by Timothy-att** [chen310/NeteaseCloudMusicTasks#128]
START RequestId: 5f7811ee-2f3e-4104-9707-dc37b3bd91bc

Init Report RequestId: 5f7811ee-2f3e-4104-9707-dc37b3bd91bc Coldstart: 625ms (PullCode: 80ms InitRuntime: 8ms InitFunction: 537ms) Memory: 128MB MemUsage: 16.16MB

ERROR RequestId: 5f7811ee-2f3e-4104-9707-dc37b3bd91bc Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/index.py", line 6, in <module>     import json5 ModuleNotFoundError: No module named 'json5'", "statusCode": 443}

END RequestId: 5f7811ee-2f3e-4104-9707-dc37b3bd91bc

Report RequestId: 5f7811ee-2f3e-4104-9707-dc37b3bd91bc Duration: 0ms Memory: 128MB MemUsage: 16.16MB

START RequestId:5f7811ee-2f3e-4104-9707-dc37b3bd91bc

ERROR RequestId:5f7811ee-2f3e-4104-9707-dc37b3bd91bc Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 6, in \u003cmodule\u003e\n    import json5\nModuleNotFoundError: No module named 'json5'","statusCode":443}

END RequestId:5f7811ee-2f3e-4104-9707-dc37b3bd91bc

Report RequestId:5f7811ee-2f3e-4104-9707-dc37b3bd91bc Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by chen310** [comment]
确定在函数的层管理中绑定了是吧？你截个图看看

**Comment by Timothy-att** [comment]
![屏幕截图 2022-03-18 203829](https://user-images.githubusercontent.com/79739717/159004419-120fb113-92a2-468d-a0df-2a0b10e7201a.png)

**Comment by Timothy-att** [comment]
@chen310

**Comment by Timothy-att** [comment]
需要填的内容都填写了，但一直都是报错

**Comment by chen310** [comment]
如果上传的依赖文件没问题，应该不会报这个错才对。你再检查检查吧，我也看不出什么问题了

**Comment by Timothy-att** [comment]
那个新建函数可不可以直接本地上传，不用github部署过去

**Comment by chen310** [comment]
可以 但是更新不方便  要更新的话还需要重新上传代码 填写配置文件

**Comment by Timothy-att** [comment]
aaa我重新从头来一次吧，目前还在上高中，没法经常回来。那个更新只要照着说明就可以自己更新了吧？ @chen310
