### ISSUE TITLE
青龙更新脚本地址不对

### ISSUE THREAD

**Issue by iminiui** [chen310/NeteaseCloudMusicTasks#13]
后面应该是 & task /ql/scripts/ql_update.py 而不是 & task /ql/scripts/chen310_NeteaseCloudMusicTasks/ql_update.py

**Comment by chen310** [comment]
> 后面应该是 & task /ql/scripts/ql_update.py 而不是 & task /ql/scripts/chen310_NeteaseCloudMusicTasks/ql_update.py

你升级一下青龙

**Comment by 2309965783** [comment]
请问青龙需要得依赖有哪些

**Comment by chen310** [comment]
> 请问青龙需要得依赖有哪些

查看requirements.txt
