### ISSUE TITLE
如何获取自动更新？

### ISSUE THREAD

**Issue by Timothy-att** [chen310/NeteaseCloudMusicTasks#130]
![屏幕截图 2022-03-18 212924](https://user-images.githubusercontent.com/79739717/159011566-9f1d5205-776b-4925-962a-df56f2550d9f.png)
ru'tu如图~

**Comment by chen310** [comment]
https://github.com/apps/pull

**Comment by matocool** [comment]
> https://github.com/apps/pull

请问下 这个安装之后，所有仓库都会自动更新吧~不光光本项目。。我这边是给全部项目授权的

**Comment by chen310** [comment]
> > https://github.com/apps/pull
> 
> 请问下 这个安装之后，所有仓库都会自动更新吧~不光光本项目。。我这边是给全部项目授权的

应该是吧，它会生成pr，需要自己merge
