### ISSUE TITLE
再次出现报错

### ISSUE THREAD

**Issue by Timothy-att** [chen310/NeteaseCloudMusicTasks#131]
START RequestId:84a4b070-2265-4799-b1f4-8cece0ed13aa

ERROR RequestId:84a4b070-2265-4799-b1f4-8cece0ed13aa Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 157, in main_handler\n    start(event, context)\n  File \"/var/user/index.py\", line 54, in start\n    config = json5.load(f)\n  File \"/opt/json5/lib.py\", line 50, in load\n    allow_duplicate_keys=allow_duplicate_keys)\n  File \"/opt/json5/lib.py\", line 82, in loads\n    raise ValueError(err)\nValueError: \u003cstring\u003e:3 Unexpected \"\"\" at column 5","statusCode":430}

END RequestId:84a4b070-2265-4799-b1f4-8cece0ed13aa

Report RequestId:84a4b070-2265-4799-b1f4-8cece0ed13aa Duration:14ms Memory:128MB MemUsage:25.261719MB

**Comment by Timothy-att** [comment]
麻木了，究竟发生了什么

**Comment by chen310** [comment]
配置文件填写有误

**Comment by Timothy-att** [comment]
是指config.json那个文件吗？ @chen310

**Comment by chen310** [comment]
是
