### ISSUE TITLE
青龙报错

### ISSUE THREAD

**Issue by ShootTau** [chen310/NeteaseCloudMusicTasks#132]
老哥那个配置文件在哪里修改呀  已经拉好了  没找到那个文件在哪里修改

**Comment by ShootTau** [comment]
python3: can't open file 'chen310_NeteaseCloudMusicTasks/ql_update.py': [Errno 2] No such file or directory

**Comment by chen310** [comment]
```shell
docker exec -it qinglong bash
ql repo https://github.com/chen310/NeteaseCloudMusicTasks.git "index.py" "" "py"
task chen310_NeteaseCloudMusicTasks/ql_update.py
```

**Comment by ShootTau** [comment]
也是显示这个python3: can't open file 'chen310_NeteaseCloudMusicTasks/ql_update.py': [Errno 2] No such file or directory

**Comment by chen310** [comment]
发一下上面命令运行结果的截图

**Comment by ShootTau** [comment]
[img]https://img30.360buyimg.com/pop/jfs/t1/111925/34/24587/448263/62353db2Ef0a7ade6/cc270cc57803f27f.png[/img]

**Comment by chen310** [comment]
你是不是把命令合并执行了，分开执行看看

**Comment by ShootTau** [comment]
![1647656615(1)](https://user-images.githubusercontent.com/87740719/159103144-aa5f5669-d9ea-40fd-86f3-83213a7f5d26.jpg)

**Comment by ShootTau** [comment]
还是不行

**Comment by chen310** [comment]
看一下 `ls /ql/scripts/chen310_NeteaseCloudMusicTasks`

**Comment by ShootTau** [comment]
![image](https://user-images.githubusercontent.com/87740719/159103247-fa12687e-61bf-4e94-a52b-8accdfd064a9.png)

**Comment by chen310** [comment]
emmm，你青龙版本是不是太低了

**Comment by ShootTau** [comment]
哈哈哈  有可能  2.9.3的  faker直接代码的的  好像不能升级

**Comment by Timothy-att** [comment]
@ShootTau 青龙是直接可以本地执行吗？

**Comment by chen310** [comment]
升级了再用吧，版本太低不能用

**Comment by ShootTau** [comment]
好的   现在升级看看

**Comment by ShootTau** [comment]
![image](https://user-images.githubusercontent.com/87740719/159111454-32d3ce07-676c-419e-a3f0-ca5612f4c72a.png)
还是不行  全升级和安装依赖也是这样

**Comment by chen310** [comment]
依赖显示安装成功？

**Comment by ShootTau** [comment]
![image](https://user-images.githubusercontent.com/87740719/159111994-dad33d57-48f7-4a23-87cf-9a5c8be89e61.png)
我重新用青龙自带的依赖管理安装了json5  就报这个了

**Comment by chen310** [comment]
用命令行安装不成功吗
```
apk add python3-dev gcc libc-dev
pip3 pycryptodomex
```

**Comment by ShootTau** [comment]
好了好了  终于在尝试几十次命令安装成功了  前几次下载到一半就断了  正常了  谢谢老哥
