### ISSUE TITLE
什么时候可以恢复账号密码登录？

### ISSUE THREAD

**Issue by Timothy-att** [chen310/NeteaseCloudMusicTasks#134]

**Comment by chen310** [comment]
不知道，估计难了

**Comment by Timothy-att** [comment]
@chen310 为什么目前账号密码登录会失败？主要原因是什么呢？

**Comment by chen310** [comment]
网易那边的限制

**Comment by Timothy-att** [comment]
@chen310 但是这个的可以正常使用账号密码https://github.com/Timothy-att/netease-cloud

**Comment by chen310** [comment]
不清楚，我有空再看看吧

**Comment by matocool** [comment]
> @chen310 但是这个的可以正常使用账号密码https://github.com/Timothy-att/netease-cloud

他这个要用API........登入是可以登入。。。但是最后全部报错。。。

**Comment by Timothy-att** [comment]
@matocool 没有报错啊。az可以正常使用

**Comment by Timothy-att** [comment]
![Screenshot_20220319_104902.jpg](https://user-images.githubusercontent.com/79739717/159103904-24a7e05a-9b8f-4147-a609-f013aeed90b2.jpg)

**Comment by Timothy-att** [comment]
从开始到现在一直都可以正常使用@matocool

**Comment by SZYiJie** [comment]
> 网易那边的限制

我这边还能用，填的就是账号密码。楼主的意思是代码把账号密码去掉了？那我还要不要从你那更新啊，旧的还能用

**Comment by Timothy-att** [comment]
> > 网易那边的限制
> 
> 我这边还能用，填的就是账号密码。楼主的意思是代码把账号密码去掉了？那我还要不要从你那更新啊，旧的还能用

没有去掉，但是目前没法用账号密码登录

**Comment by ChenXue992** [comment]
我可以用账号密码啊

**Comment by matocool** [comment]
> 

2022.03.16-11:17:40   用户任务执行中断,请检查账号密码是否正确

**Comment by chen310** [comment]
暂时解决，更新代码后应该就能用账号密码登录了
