### ISSUE TITLE
老哥，之前正常用，今天拉取新代码就这样了

### ISSUE THREAD

**Issue by SG121** [chen310/NeteaseCloudMusicTasks#14]
## 开始执行... 2022-01-06 17:28:16

Traceback (most recent call last):
  File "index.py", line 281, in <module>
    start({}, {})
  File "index.py", line 41, in start
    config = json5.load(f)
  File "/usr/lib/python3.8/site-packages/json5/lib.py", line 46, in load
    return loads(s, encoding=encoding, cls=cls, object_hook=object_hook,
  File "/usr/lib/python3.8/site-packages/json5/lib.py", line 82, in loads
    raise ValueError(err)
ValueError: <string>:2 Unexpected """ at column 5

## 执行结束... 2022-01-06 17:28:17 耗时 1 秒

**Comment by chen310** [comment]
> ## 开始执行... 2022-01-06 17:28:16
> 
> Traceback (most recent call last):
>   File "index.py", line 281, in <module>
>     start({}, {})
>   File "index.py", line 41, in start
>     config = json5.load(f)
>   File "/usr/lib/python3.8/site-packages/json5/lib.py", line 46, in load
>     return loads(s, encoding=encoding, cls=cls, object_hook=object_hook,
>   File "/usr/lib/python3.8/site-packages/json5/lib.py", line 82, in loads
>     raise ValueError(err)
> ValueError: <string>:2 Unexpected """ at column 5
> 
> ## 执行结束... 2022-01-06 17:28:17 耗时 1 秒

是不是配置文件出错了？

**Comment by SG121** [comment]
配置文件我换了新的，重新填写的，开始的时候提示下边这个，然后我把配置文件更新了最新的，就提示上边的那个
## 开始执行... 2022-01-06 15:13:00

Traceback (most recent call last):
  File "index.py", line 281, in <module>
    start({}, {})
  File "index.py", line 53, in start
    if user_config['enable'] == False:
KeyError: 'enable'

## 执行结束... 2022-01-06 15:13:02 耗时 2 秒

**Comment by chen310** [comment]
> 配置文件我换了新的，重新填写的，开始的时候提示下边这个，然后我把配置文件更新了最新的，就提示上边的那个
> ## 开始执行... 2022-01-06 15:13:00
> 
> Traceback (most recent call last):
>   File "index.py", line 281, in <module>
>     start({}, {})
>   File "index.py", line 53, in start
>     if user_config['enable'] == False:
> KeyError: 'enable'
> 
> ## 执行结束... 2022-01-06 15:13:02 耗时 2 秒

奇怪，更新代码之后，配置文件应该也会自动更新才对啊。那现在的问题就是配置文件有问题，你修改一下吧，或者把配置文件删了，重新拉取

**Comment by SG121** [comment]
可以了  配置文件出错了
