### ISSUE TITLE
云圈id问题已经部署了还是获取失败是什么原因？

### ISSUE THREAD

**Issue by wyh0326** [chen310/NeteaseCloudMusicTasks#144]

**Comment by wyh0326** [comment]
![image](https://user-images.githubusercontent.com/65211335/159173451-b7db9ec0-fcaf-4fa5-9009-fab437c4e5fb.png)

**Comment by wyh0326** [comment]
![image](https://user-images.githubusercontent.com/65211335/159173486-9759bb24-27c2-467b-bc5a-8b567d092fda.png)

**Comment by chen310** [comment]
确认是填到 `config.json` 这个文件里吗？

**Comment by wyh0326** [comment]
> 确认是填到 `config.json` 这个文件里吗？

![image](https://user-images.githubusercontent.com/65211335/159199794-16284fad-b4fa-4065-9de8-7a9dc99a36b8.png)

**Comment by chen310** [comment]
什么版本的？更新代码试试

**Comment by wyh0326** [comment]
> 

2.19的吧

**Comment by wyh0326** [comment]
好的
我试试

**Comment by wyh0326** [comment]
到部署这一步怎么都没有啊
![image](https://user-images.githubusercontent.com/65211335/159202998-aac638a9-bdd1-4b08-8f30-db1393b47371.png)

**Comment by chen310** [comment]
仔细阅读文档

![msedge_rEq1rvrPfg](https://user-images.githubusercontent.com/33364396/159218958-40efa96f-b184-4950-aa22-8eaa719b99e0.png)
