### ISSUE TITLE
任务跑了可结果是测试失败

### ISSUE THREAD

**Issue by wzt3266158775** [chen310/NeteaseCloudMusicTasks#145]
![屏幕截图(134)](https://user-images.githubusercontent.com/101856760/159195787-16013b2b-1c4b-4ffb-829e-9854f1a928d1.png)
如图任务跑了最后提示失败，推送也没有推送

**Comment by chen310** [comment]
最多只能运行 900 秒，你已经超时了。要么是刷播放量刷得太多，要么是设置了太多个账号

**Comment by wzt3266158775** [comment]
好的好的，知道了，谢谢
