### ISSUE TITLE
大佬我在发布mlog那一段填写了歌曲id还是显示请填写歌曲id

### ISSUE THREAD

**Issue by Mriccou** [chen310/NeteaseCloudMusicTasks#147]
![image](https://user-images.githubusercontent.com/101546131/159208441-15f20488-208c-4857-92f1-ffefd46790ee.png)
![image](https://user-images.githubusercontent.com/101546131/159208443-c23d9dac-78d4-4116-b746-204bd55bd49b.png)

**Comment by wyh0326** [comment]
你可以试试那个随机的号码

**Comment by chen310** [comment]
请确认是在 `config.json` 而不是 `config.example.json` 填写的

**Comment by Mriccou** [comment]
可以了感谢大佬
