### ISSUE TITLE
大佬 怎么更新啊 详细的过程 

### ISSUE THREAD

**Issue by michereyue** [chen310/NeteaseCloudMusicTasks#148]
找不到那个文章里面的更新入口 从网上找的更新教程也没成功 感谢🙏 希望可以指导

**Comment by xx668888** [comment]
顺便求一个 docker 怎么更新最新代码   有大佬知道的，说下

**Comment by michereyue** [comment]
> 找不到那个文章里面的更新入口从网上找的更新教程也没有成功感谢🙏希望可以指

已解决 要在自己的fork中
