### ISSUE TITLE
网易云自动运行报错

### ISSUE THREAD

**Issue by Cigarr** [chen310/NeteaseCloudMusicTasks#150]
青龙面板运行的网易云自动脚本，报如图所示错误，百度一番未果，求解
![image](https://user-images.githubusercontent.com/56327771/159290054-73d51e8f-ba19-478a-bd6b-7ee81c0e64a6.png)
青龙面板版本
 2.11.3

**Comment by chen310** [comment]
`config.json` 填写出错

**Comment by chen310** [comment]
Duplicate of #14

**Comment by Cigarr** [comment]
嗯嗯，谢谢大佬指点，又修改了一下，发现是cookie填错了，重新填了，运行正常了
