### ISSUE TITLE
云函数部署 测试失败  执行日志是这样的

### ISSUE THREAD

**Issue by cf48rty** [chen310/NeteaseCloudMusicTasks#151]
START RequestId: 3bf99ba7-f612-416a-98ac-f5b1e3834d78

Init Report RequestId: 3bf99ba7-f612-416a-98ac-f5b1e3834d78 Coldstart: 700ms (PullCode: 123ms InitRuntime: 5ms InitFunction: 572ms) Memory: 128MB MemUsage: 16.42MB

Report RequestId: 3bf99ba7-f612-416a-98ac-f5b1e3834d78 Duration: 0ms Memory: 128MB MemUsage: 16.42MB

**Comment by chen310** [comment]
什么都看不出来，你自己上传代码的？

**Comment by cf48rty** [comment]
是的 我直接克隆下你的代码 上传上去 然后装了依赖 然后改了配置文件

**Comment by chen310** [comment]
压缩包路径不对 从这里下载 https://github.com/chen310/NeteaseCloudMusicTasks/actions/workflows/upload.yml

**Comment by cf48rty** [comment]
从那里下载什么   那是你的actions

**Comment by chen310** [comment]
![msedge_3rPQeAYTGg](https://user-images.githubusercontent.com/33364396/159392326-6e980f4b-1d8c-4ccd-841d-54d79093060c.png)

**Comment by cf48rty** [comment]
![image](https://user-images.githubusercontent.com/76237137/159392447-8379089a-d408-43d1-9e3b-3373b173ec96.png)

**Comment by chen310** [comment]
![msedge_FZAIx0Ndpt](https://user-images.githubusercontent.com/33364396/159392547-4c9ef58b-b1ab-45d9-a093-da98986d79f7.png)

**Comment by cf48rty** [comment]
START RequestId: bc285eab-5ba7-404d-a2dd-447ab160578c

ERROR RequestId: bc285eab-5ba7-404d-a2dd-447ab160578c Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/index.py", line 10, in <module>     import json5 ModuleNotFoundError: No module named 'json5'", "statusCode": 443}

END RequestId: bc285eab-5ba7-404d-a2dd-447ab160578c

Report RequestId: bc285eab-5ba7-404d-a2dd-447ab160578c Duration: 0ms Memory: 128MB MemUsage: 16.08MB

**Comment by chen310** [comment]
#28

**Comment by cf48rty** [comment]
ERROR RequestId:b83e68f3-5f18-4b58-9c7b-426f741b1f42 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 163, in main_handler\n    start(event, context)\n  File \"/var/user/index.py\", line 73, in start\n    if not user_config['enable']:\nKeyError: 'enable'","statusCode":430}

END RequestId:b83e68f3-5f18-4b58-9c7b-426f741b1f42

Report RequestId:b83e68f3-5f18-4b58-9c7b-426f741b1f42 Duration:5189ms Memory:128MB MemUsage:38.285156MB

**Comment by chen310** [comment]
请修改而不是删除配置文件里的内容

**Comment by cf48rty** [comment]
谢谢，已经解决
