### ISSUE TITLE
请问青龙的config.json在哪

### ISSUE THREAD

**Issue by dagenduizhanga** [chen310/NeteaseCloudMusicTasks#157]
只看到config.example.json文件，我在里面填写信息，跑不起来
![image](https://user-images.githubusercontent.com/85776844/159663248-39737514-66ae-4148-a6ee-44f77473b4c6.png)

**Comment by chen310** [comment]
复制为 `config.json`

**Comment by dagenduizhanga** [comment]
> 也试过，后面尝试了下云函数倒是可以了，就是有点好奇，青龙哪里操作错误了

![image](https://user-images.githubusercontent.com/85776844/159671946-07c669fe-d063-4053-9e00-361805e2e6e3.png)

**Comment by chen310** [comment]
在脚本管理里，不是在配置文件里

**Comment by dagenduizhanga** [comment]
> 你是怎么部署的

我是直接按照，https://github.com/chen310/NeteaseCloudMusicTasks#%E5%A4%9A%E8%B4%A6%E5%8F%B7，就是到config.json那步，运行完生成目录文件及依赖后，我直接复制config.example.json到青龙的配置文件目录下，然后在面板下面填写信息

**Comment by chen310** [comment]
![msedge_BkfBaMboZX](https://user-images.githubusercontent.com/33364396/159673247-ac302adc-fc19-4570-a82b-dcd849740d06.png)

**Comment by dagenduizhanga** [comment]
> ![msedge_BkfBaMboZX](https://user-images.githubusercontent.com/33364396/159673247-ac302adc-fc19-4570-a82b-dcd849740d06.png)

感谢，糊涂了，填好信息后提示这个
![image](https://user-images.githubusercontent.com/85776844/159694579-c2fab6e3-2cdb-4f22-8def-09d0de0a25c6.png)

**Comment by chen310** [comment]
配置文件 `config.json` 填写出错

**Comment by dagenduizhanga** [comment]
> 配置文件 `config.json` 填写出错

哈哈哈十分感谢，爱你么么哒
