### ISSUE TITLE
青龙报错，用的最新版青龙

### ISSUE THREAD

**Issue by fuduxixi** [chen310/NeteaseCloudMusicTasks#16]
Traceback (most recent call last):
  File "index.py", line 281, in <module>
    start({}, {})
  File "index.py", line 41, in start
    config = json5.load(f)
  File "/usr/lib/python3.8/site-packages/json5/lib.py", line 46, in load
    return loads(s, encoding=encoding, cls=cls, object_hook=object_hook,
  File "/usr/lib/python3.8/site-packages/json5/lib.py", line 82, in loads
    raise ValueError(err)
ValueError: <string>:2 Unexpected """ at column 5

**Comment by chen310** [comment]
> Traceback (most recent call last): File "index.py", line 281, in start({}, {}) File "index.py", line 41, in start config = json5.load(f) File "/usr/lib/python3.8/site-packages/json5/lib.py", line 46, in load return loads(s, encoding=encoding, cls=cls, object_hook=object_hook, File "/usr/lib/python3.8/site-packages/json5/lib.py", line 82, in loads raise ValueError(err) ValueError: :2 Unexpected """ at column 5

查看配置文件填写是否有问题
