### ISSUE TITLE
为啥建玩层之后在函数服务里面没有.

### ISSUE THREAD

**Issue by iYUEBANi** [chen310/NeteaseCloudMusicTasks#160]

**Comment by chen310** [comment]
可能时新建层的时候运行环境选择的不是python3.6，或者层和函数不在同一个地域

**Comment by iYUEBANi** [comment]
> 可能时新建层的时候运行环境选择的不是python3.6，或者层和函数不在同一个地域

感谢你的回复，问题以解决.
