### ISSUE TITLE
如何下载最新代码

### ISSUE THREAD

**Issue by ALKSDJ0000** [chen310/NeteaseCloudMusicTasks#161]

**Comment by chen310** [comment]
到 [Actions](https://github.com/chen310/NeteaseCloudMusicTasks/actions/workflows/upload.yml) 中点进第一个

![msedge_AS8fD9nYJh](https://user-images.githubusercontent.com/33364396/159928603-1f2ba9f6-0ee9-4c46-9989-1c8953e0c92f.png)

然后下载

![msedge_NwVzuAVux3](https://user-images.githubusercontent.com/33364396/159928692-3697a546-92e2-4139-9571-4150fdaf4c47.png)
