### ISSUE TITLE
日志里没有看到有推送相关的消息，建议加上

### ISSUE THREAD

**Issue by GLORYFeonix** [chen310/NeteaseCloudMusicTasks#166]
使用的是telegram，id我填的是手机号不知对不对？测试的时候日志可以看到所有任务都成功了，但没有收到推送。不知道是我填错了不应该填手机号还是日志里就没有推送相关的消息？

**Comment by GLORYFeonix** [comment]
telegram确实也没有收到推送

**Comment by chen310** [comment]
看日志

**Comment by mybdye** [comment]
> 使用的是telegram，id我填的是手机号不知对不对？测试的时候日志可以看到所有任务都成功了，但没有收到推送。不知道是我填错了不应该填手机号还是日志里就没有推送相关的消息？

大佬你先去了解下 tg 推送相关知识呀， `user id`  和 `bot token` 。

**Comment by chen310** [comment]
id 不是手机号
