### ISSUE TITLE
关于网易云音乐人观看课程

### ISSUE THREAD

**Issue by W4J1e** [chen310/NeteaseCloudMusicTasks#177]
您好，网易云音乐人任务中的观看课程需要观看两个才能获得云豆，我部署在服务器上，推送情况和网易云音乐任务里显示运行之后只学习了一次，请问能否考虑优化一下，谢谢。

**Comment by chen310** [comment]
这是周任务，一天一次即可

**Comment by W4J1e** [comment]
> 这是周任务，一天一次即可

了解了，谢谢！
