### ISSUE TITLE
pushplush多账号推送

### ISSUE THREAD

**Issue by Muggles001** [chen310/NeteaseCloudMusicTasks#179]
我第二个账号设置了token，第一个账号的token填写在下面下面的pushplush推送打开了，也关闭合并了，但是收到推送的只有第一个账号
![](https://pic.imgdb.cn/item/6242b07927f86abb2ab99f2d.png)
![](https://pic.imgdb.cn/item/6242b08427f86abb2ab9bcf2.png)

**Comment by chen310** [comment]
两个地方具体怎么设置的，打个码贴一下图，或放上代码

**Comment by Muggles001** [comment]
![](https://pic.imgdb.cn/item/6242b45427f86abb2ac3e529.png)
![](https://pic.imgdb.cn/item/6242b45427f86abb2ac3e529.png)
老哥帮忙看下顺便问下，一个账号做回复粉丝等任务一个不做怎么设置

**Comment by chen310** [comment]
你这个图片怎么只有一部分？

**Comment by Muggles001** [comment]
这图床有点垃圾
https://pic.imgdb.cn/item/6242b46527f86abb2ac41078.png
https://pic.imgdb.cn/item/6242b45427f86abb2ac3e529.png
直接点进去看吧

**Comment by chen310** [comment]
pushplus 里设置的是token，怎么第二个账号成了key了

**Comment by chen310** [comment]
你第二个账号没有单独设置音乐人任务

**Comment by Muggles001** [comment]
我说的，煞笔了，我直接复制的你的教程代码，老哥再问下如何一个做回复粉丝的任务，一个不做

**Comment by chen310** [comment]
上面已经回复了，需要单独设置音乐人任务

**Comment by Muggles001** [comment]
那下面那个音乐人任务开不开，我第一个账号不做，第二个做

**Comment by chen310** [comment]
都要开

**Comment by Muggles001** [comment]
OK。感谢了
