### ISSUE TITLE
青龙和本地都不能运行 好难啊

### ISSUE THREAD

**Issue by huge283** [chen310/NeteaseCloudMusicTasks#20]
Traceback (most recent call last):
  File "index.py", line 9, in <module>
    from user import User
  File "/ql/scripts/chen310_NeteaseCloudMusicTasks/user.py", line 7, in <module>
    from api import NetEase
  File "/ql/scripts/chen310_NeteaseCloudMusicTasks/api.py", line 7, in <module>
    from encrypt import encrypted_request
  File "/ql/scripts/chen310_NeteaseCloudMusicTasks/encrypt.py", line 9, in <module>
    from Cryptodome.Cipher import AES
ModuleNotFoundError: No module named 'Cryptodome'

**Comment by chen310** [comment]
> Traceback (most recent call last):
>   File "index.py", line 9, in <module>
>     from user import User
>   File "/ql/scripts/chen310_NeteaseCloudMusicTasks/user.py", line 7, in <module>
>     from api import NetEase
>   File "/ql/scripts/chen310_NeteaseCloudMusicTasks/api.py", line 7, in <module>
>     from encrypt import encrypted_request
>   File "/ql/scripts/chen310_NeteaseCloudMusicTasks/encrypt.py", line 9, in <module>
>     from Cryptodome.Cipher import AES
> ModuleNotFoundError: No module named 'Cryptodome'

依赖没有安装成功，还是在云函数上运行吧

**Comment by flipped-1121** [comment]
![image](https://user-images.githubusercontent.com/61106285/149719155-08f8f058-ca0d-4280-8583-e0fb1e3889b6.png)

**Comment by imkcptest** [comment]
![image](https://user-images.githubusercontent.com/97370793/151650254-3491ecc6-6d7d-43f3-90f1-fb009d5cb624.png)怎么回事？

**Comment by chen310** [comment]
> ![image](https://user-images.githubusercontent.com/97370793/151650254-3491ecc6-6d7d-43f3-90f1-fb009d5cb624.png)怎么回事？

配置文件填错了

**Comment by chen310** [comment]
> <img width="524" alt="截屏2022-02-15 下午10 14 49" src="https://user-images.githubusercontent.com/20557518/154079501-897c0c48-cef7-4ad8-a234-737d10c0acb9.png">
> 同样的问题，python依赖都安装好了

检查一下配置文件有没有错
