### ISSUE TITLE
函数服务中并无刚刚创建的函数！！

### ISSUE THREAD

**Issue by matocool** [chen310/NeteaseCloudMusicTasks#22]
添加依赖
下载依赖文件 ，也可以自己用 pip 下载依赖，然后打包。然后在高级能力新建层，层名称可以自己任意填写，然后上传刚刚下载的压缩包，点击添加运行环境，选择Python3.6。在函数服务点进刚刚创建的函数，点击上方的层管理，点击绑定，选择刚刚创建的层。

以在创建层，但是按步骤，函数服务里面并没有新创的函数啊。

难道是要在函数服务里面自己新创一个吗？？

**Comment by matocool** [comment]
![image](https://user-images.githubusercontent.com/83129369/149657024-e9f56966-7f2f-4ddc-b190-f741eb59061a.png)


![image](https://user-images.githubusercontent.com/83129369/149657029-1498e293-4e65-4fc0-b25a-4e1ce9110d39.png)

**Comment by chen310** [comment]
> ![image](https://user-images.githubusercontent.com/83129369/149657024-e9f56966-7f2f-4ddc-b190-f741eb59061a.png)
> 
> 
> ![image](https://user-images.githubusercontent.com/83129369/149657029-1498e293-4e65-4fc0-b25a-4e1ce9110d39.png)
> 

在github actions中部署了吗

**Comment by matocool** [comment]
> > ![image](https://user-images.githubusercontent.com/83129369/149657024-e9f56966-7f2f-4ddc-b190-f741eb59061a.png)
> > ![image](https://user-images.githubusercontent.com/83129369/149657029-1498e293-4e65-4fc0-b25a-4e1ce9110d39.png)
> 
> 在github actions中部署了吗

自动部署
更新代码后将会自动触发 workflow，部署到腾讯云函数。到 Actions 中可以查看部署进度。

感谢作者大大，已解决。。。是我傻瓜，以为fork了就会自动部署。第一次要手动、

**Comment by matocool** [comment]
/* 打卡刷歌 */
        "daka": {
            /* 是否开启任务 */
            "enable": false,
            /* 满级时自动停止 */
            "full_stop": true,
            /* 是否开启自动打卡，该模式下song_number和sleep_time参数将失效 */
            "auto": true,
            /* 对打卡误差的容忍度，在自动打卡模式下有效 */
            /* 0表示必须要达到300首才停止打卡，10表示达到290首就可以停止打卡 */
            /* 可以设置为10左右，避免因为误差导致不停打卡 */
            "tolerance": 10,
            /* 歌曲数 */
            "song_number": 300,
            /* 休眠时间 */
            "sleep_time": 10,
            "upload_num": 300


---------------------------------------------------
顺便请教下这一段，我打卡刷歌。我已经满级了。。就是在刷听歌量。

是不是改成，

/* 是否开启任务 */
            "enable": true,
            /* 满级时自动停止 */
            "full_stop": false,

**Comment by chen310** [comment]
> /* 打卡刷歌 */
>         "daka": {
>             /* 是否开启任务 */
>             "enable": false,
>             /* 满级时自动停止 */
>             "full_stop": true,
>             /* 是否开启自动打卡，该模式下song_number和sleep_time参数将失效 */
>             "auto": true,
>             /* 对打卡误差的容忍度，在自动打卡模式下有效 */
>             /* 0表示必须要达到300首才停止打卡，10表示达到290首就可以停止打卡 */
>             /* 可以设置为10左右，避免因为误差导致不停打卡 */
>             "tolerance": 10,
>             /* 歌曲数 */
>             "song_number": 300,
>             /* 休眠时间 */
>             "sleep_time": 10,
>             "upload_num": 300
> 
> 
> ---------------------------------------------------
> 顺便请教下这一段，我打卡刷歌。我已经满级了。。就是在刷听歌量。
> 
> 是不是改成，
> 
> /* 是否开启任务 */
>             "enable": true,
>             /* 满级时自动停止 */
>             "full_stop": false,

对
