### ISSUE TITLE
再麻烦大佬一下，谢谢

### ISSUE THREAD

**Issue by matocool** [chen310/NeteaseCloudMusicTasks#23]
/* 打卡刷歌 /
"daka": {
/ 是否开启任务 /
"enable": false,
/ 满级时自动停止 /
"full_stop": true,
/ 是否开启自动打卡，该模式下song_number和sleep_time参数将失效 /
"auto": true,
/ 对打卡误差的容忍度，在自动打卡模式下有效 /
/ 0表示必须要达到300首才停止打卡，10表示达到290首就可以停止打卡 /
/ 可以设置为10左右，避免因为误差导致不停打卡 /
"tolerance": 10,
/ 歌曲数 /
"song_number": 300,
/ 休眠时间 */
"sleep_time": 10,
"upload_num": 300

顺便请教下这一段，我打卡刷歌。我已经满级了。。就是在刷听歌量。

是不是改成，

/* 是否开启任务 /
"enable": true,
/ 满级时自动停止 */
"full_stop": false,

**Comment by chen310** [comment]
https://github.com/chen310/NeteaseCloudMusicTasks/issues/22#issuecomment-1013898460
