### ISSUE TITLE
青龙运行异常

### ISSUE THREAD

**Issue by creboy** [chen310/NeteaseCloudMusicTasks#24]
## 更新任务状态成功
Traceback (most recent call last):
  File "chen310_NeteaseCloudMusicTasks_index.py", line 281, in <module>
    start()
  File "chen310_NeteaseCloudMusicTasks_index.py", line 40, in start
    with open('./config.json', 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './config.json'
## 更新任务状态成功

**Comment by flipped-1121** [comment]
未新建 ```config.json``` 配置文件。

**Comment by chen310** [comment]
> 未新建 ```config.json``` 配置文件。

升级青龙。

**Comment by chen310** [comment]
> ## 开始执行... 2022-01-17 12:52:57
> 
> ## 更新任务状态成功
> Traceback (most recent call last):
>   File "chen310_NeteaseCloudMusicTasks_index.py", line 281, in <module>
>     start()
>   File "chen310_NeteaseCloudMusicTasks_index.py", line 40, in start
>     with open('./config.json', 'r', encoding='utf-8') as f:
> FileNotFoundError: [Errno 2] No such file or directory: './config.json'
> ## 更新任务状态成功

请升级青龙

**Comment by 896965554** [comment]
日志-index.py
## 开始执行... 2022-02-15 10:43:01

Traceback (most recent call last):
  File "/ql/scripts/chen310_NeteaseCloudMusicTasks/index.py", line 6, in <module>
    import json5
ModuleNotFoundError: No module named 'json5'

## 执行结束... 2022-02-15 10:43:02 耗时 1 秒

**Comment by flipped-1121** [comment]
> 日志-index.py
> 
> ## 开始执行... 2022-02-15 10:43:01
> Traceback (most recent call last): File "/ql/scripts/chen310_NeteaseCloudMusicTasks/index.py", line 6, in import json5 ModuleNotFoundError: No module named 'json5'
> 
> ## 执行结束... 2022-02-15 10:43:02 耗时 1 秒

https://github.com/chen310/NeteaseCloudMusicTasks/issues/20#issuecomment-1014184847
