### ISSUE TITLE
青龙面板PushPlus不成功

### ISSUE THREAD

**Issue by Tx1nn** [chen310/NeteaseCloudMusicTasks#25]
pushplus一直不发送
![image](https://user-images.githubusercontent.com/91643568/149720961-f3d8865d-d01d-4e97-886e-2a2420429e33.png)
![image](https://user-images.githubusercontent.com/91643568/149721014-ec107044-1c98-412b-acf2-243a861eeadc.png)
"stopPushOnAPIGateway": false,也改了false
![image](https://user-images.githubusercontent.com/91643568/149721102-c33be0c8-7111-4f9f-8f1e-cb97edb55e2b.png)
求大佬指教一下

**Comment by chen310** [comment]
> pushplus一直不发送
> ![image](https://user-images.githubusercontent.com/91643568/149720961-f3d8865d-d01d-4e97-886e-2a2420429e33.png)
> ![image](https://user-images.githubusercontent.com/91643568/149721014-ec107044-1c98-412b-acf2-243a861eeadc.png)
> "stopPushOnAPIGateway": false,也改了false
> ![image](https://user-images.githubusercontent.com/91643568/149721102-c33be0c8-7111-4f9f-8f1e-cb97edb55e2b.png)
> 求大佬指教一下

请确认使用的是 http://www.pushplus.plus

**Comment by Tx1nn** [comment]
![image](https://user-images.githubusercontent.com/91643568/149732315-6084474f-3375-4587-a092-d52d610d1d0c.png)
就是这个啊 官网测试 能给我微信推送消息

**Comment by chen310** [comment]
> ![image](https://user-images.githubusercontent.com/91643568/149732315-6084474f-3375-4587-a092-d52d610d1d0c.png) 就是这个啊 官网测试 能给我微信推送消息

topic为空时能发送吗
