### ISSUE TITLE
打卡信息都是0首

### ISSUE THREAD

**Issue by Lynds-007** [chen310/NeteaseCloudMusicTasks#27]
#### 打卡信息
- 本次打卡数: 0首
- 听歌总数: 6229首
- 温馨提示: 数据更新可能有延时，[点击查看最新数据]
-

**Comment by chen310** [comment]
> #### 打卡信息
> - 本次打卡数: 0首
> - 听歌总数: 6229首
> - 温馨提示: 数据更新可能有延时，[点击查看最新数据]
> - 

今天呢？不是0了吧
