### ISSUE TITLE
云函数运行报错

### ISSUE THREAD

**Issue by 123321abccba1** [chen310/NeteaseCloudMusicTasks#28]
START RequestId: c78ca8ea14a3677c71692407657bace3

Init Report RequestId: c78ca8ea14a3677c71692407657bace3 Coldstart: 838ms (PullCode: 113ms InitRuntime: 11ms InitFunction: 714ms) Memory: 128MB MemUsage: 16.73MB

ERROR RequestId: c78ca8ea14a3677c71692407657bace3 Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/index.py", line 6, in <module>     import json5 ModuleNotFoundError: No module named 'json5'", "statusCode": 443}

END RequestId: c78ca8ea14a3677c71692407657bace3

Report RequestId: c78ca8ea14a3677c71692407657bace3 Duration: 0ms Memory: 128MB MemUsage: 16.73MB

START RequestId:c78ca8ea14a3677c71692407657bace3

ERROR RequestId:c78ca8ea14a3677c71692407657bace3 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 6, in \u003cmodule\u003e\n    import json5\nModuleNotFoundError: No module named 'json5'","statusCode":443}

END RequestId:c78ca8ea14a3677c71692407657bace3

Report RequestId:c78ca8ea14a3677c71692407657bace3 Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by chen310** [comment]
[添加依赖](https://github.com/chen310/NeteaseCloudMusicTasks#%E6%B7%BB%E5%8A%A0%E4%BE%9D%E8%B5%96)

**Comment by clownwait** [comment]
> [添加](https://github.com/chen310/NeteaseCloudMusicTasks#%E6%B7%BB%E5%8A%A0%E4%BE%9D%E8%B5%96)
不好意思，没仔细阅读文档，感谢解答！问题已经解决

**Comment by Timothy-att** [comment]
我也出错aaa，这是怎么回事

**Comment by chen310** [comment]
> 我也出错aaa，这是怎么回事

上面已经回复了，需要依赖，添加层

**Comment by Timothy-att** [comment]
添加了，还是不行

**Comment by 123321abccba1** [comment]
我添加依赖后正常了

**Comment by chen310** [comment]
> 添加了，还是不行

可能时文件上传错了，仔细看一下你上传的是哪个文件

**Comment by Timothy-att** [comment]
@chen310 我再试一遍

**Comment by Timothy-att** [comment]
怎么还是会报错

**Comment by chen310** [comment]
@Timothy-att 你下载的是这个文件吗 https://chen10.lanzouo.com/igHXzxf8wjc

**Comment by Timothy-att** [comment]
依赖文件是dependencies吗？

**Comment by Timothy-att** [comment]
是

**Comment by Timothy-att** [comment]
@chen310 我找到原因了，我叉的不是你的项目
