### ISSUE TITLE
为什么云函数运行完不推送？

### ISSUE THREAD

**Issue by sinner7620** [chen310/NeteaseCloudMusicTasks#30]
已打开推送开关，并且设置都没问题。但是在测试执行完后没有推送。（另外可不可以考虑加入Qmsg推送）
![image](https://user-images.githubusercontent.com/62606659/151160208-5378425e-a5b9-421c-ab99-c099047ef022.png)

**Comment by chen310** [comment]
看看有无报错

**Comment by sinner7620** [comment]
看了发现pushplus的推送接口网址更新了，我改了一下可以了
