### ISSUE TITLE
Github Action自动部署到SCF失败

### ISSUE THREAD

**Issue by DoveBoy** [chen310/NeteaseCloudMusicTasks#35]
现在通过GA部署到SCF失败

![image](https://user-images.githubusercontent.com/19201447/153414725-1f2ed6b6-e10e-4eaa-982d-816db7cc77d5.png)
![image](https://user-images.githubusercontent.com/19201447/153414692-17eca18b-0130-4642-9082-01ec597e7710.png)

**Comment by chen310** [comment]
到云函数中删掉相应的函数，然后重新部署。可以先备份一下配置文件，重新部署后再拷进去

**Comment by DoveBoy** [comment]
@chen310 已删除SCF相应的函数，按照全新方式部署，依旧报错，报错内容完全一样

**Comment by chen310** [comment]
试试添加`FUNCTION_NAME`这个secret来更换函数名，然后部署到这个新的函数上

**Comment by DoveBoy** [comment]
> 试试添加`FUNCTION_NAME`这个secret来更换函数名，然后部署到这个新的函数上

目前测试不添加`FUNCTION_NAME`变量，以默认函数名部署是失败的，同时`FUNCTION_NAME`设置`NeteaseCloudMusicTasks`也是失败的。只有将`FUNCTION_NAME`变量设置成其他函数名才能部署成功

**Comment by Faker-233** [comment]
![image](https://user-images.githubusercontent.com/76934098/155091957-0fbffadf-2900-47dc-9703-053399f905cb.png)
这个问题怎么解决

**Comment by chen310** [comment]
> ![image](https://user-images.githubusercontent.com/76934098/155091957-0fbffadf-2900-47dc-9703-053399f905cb.png)
> 这个问题怎么解决

更新代码到最新版本
