### ISSUE TITLE
云函数运行报错

### ISSUE THREAD

**Issue by X-nancy** [chen310/NeteaseCloudMusicTasks#36]
START RequestId: b6adc955-4757-4e90-b620-3e0e320ac87d

Init Report RequestId: b6adc955-4757-4e90-b620-3e0e320ac87d Coldstart: 1606ms (PullCode: 197ms InitRuntime: 115ms InitFunction: 1294ms) Memory: 128MB MemUsage: 16.16MB

ERROR RequestId: b6adc955-4757-4e90-b620-3e0e320ac87d Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/index.py", line 9, in <module>     from user import User   File "/var/user/user.py", line 6, in <module>     from api import NetEase   File "/var/user/api.py", line 7, in <module>     from encrypt import encrypted_request ModuleNotFoundError: No module named 'encrypt'", "statusCode": 443}

END RequestId: b6adc955-4757-4e90-b620-3e0e320ac87d

Report RequestId: b6adc955-4757-4e90-b620-3e0e320ac87d Duration: 0ms Memory: 128MB MemUsage: 16.16MB

START RequestId:b6adc955-4757-4e90-b620-3e0e320ac87d

ERROR RequestId:b6adc955-4757-4e90-b620-3e0e320ac87d Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 9, in \u003cmodule\u003e\n    from user import User\n  File \"/var/user/user.py\", line 6, in \u003cmodule\u003e\n    from api import NetEase\n  File \"/var/user/api.py\", line 7, in \u003cmodule\u003e\n    from encrypt import encrypted_request\nModuleNotFoundError: No module named 'encrypt'","statusCode":443}

END RequestId:b6adc955-4757-4e90-b620-3e0e320ac87d

Report RequestId:b6adc955-4757-4e90-b620-3e0e320ac87d Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by X-nancy** [comment]
你好，前一个月一直运行都没问题，问题是这几天出现的，重新部署、添加依赖还是调用失败QAQ

**Comment by chen310** [comment]
是更新后才出现这个情况的吗？

**Comment by X-nancy** [comment]
> 是更新后才出现这种情况的吗？

大概是8号就开始报错了吧，7号还有签到通知
![image](https://user-images.githubusercontent.com/45621151/153552358-53f4d697-e950-44dd-a3c6-f8c105633fbd.png)
github4天前更新过一次，会不会是这个原因呢？

**Comment by chen310** [comment]
可以使用`FUNCTION_NAME`来更改函数名，然后重新部署到新的函数。如果成功了再把配置文件拷过去，然后删掉之前的函数

**Comment by X-nancy** [comment]
> 可以使用`FUNCTION_NAME`来更改函数名，然后重新部署到新的函数。如果成功了再把配置文件拷过去，然后删掉之前的函数
好的，我试试

**Comment by Jakob-Boy** [comment]
我也出现同样报错，后来仔细阅读文档发现是忘记添加依赖，添加后一切正常！

**Comment by X-nancy** [comment]
> 我也出现同样报错，后来仔细阅读文档发现是忘记添加依赖，添加后一切正常！

我是运行一个月多，突然就这样子的QAQ，使用FUNCTION_NAME来更改函数名重新部署就好了
