### ISSUE TITLE
Telegram推送疑似未生效

### ISSUE THREAD

**Issue by Jakob-Boy** [chen310/NeteaseCloudMusicTasks#37]
Hello，已经设置telegram通知并保存(下图)，测试运行后日志未显示任何推送成功or失败的消息(当然tgbot也未受到任何消息)，随后测试pushplus有推送并且日志显示，麻烦作者查看一下，是否为程序问题
- 运行环境：云函数
- 地域：hk
<a href="https://imgtu.com/i/HdMWef"><img src="https://s4.ax1x.com/2022/02/11/HdMWef.png" alt="HdMWef.png" border="0" /></a>
<a href="https://imgtu.com/i/HdMuLV"><img src="https://s4.ax1x.com/2022/02/11/HdMuLV.png" alt="HdMuLV.png" border="0" /></a>

**Comment by chen310** [comment]
更新一下代码再试试

**Comment by wmyfelix** [comment]
https://github.com/chen310/NeteaseCloudMusicTasks/pull/48  
上次没修全诶

**Comment by chen310** [comment]
> https://github.com/chen310/NeteaseCloudMusicTasks/pull/48  
> 上次没修全诶  

确实

**Comment by Jakob-Boy** [comment]
非常感谢两位dalao，重新部署新版本已经修复（原来是判断条件少了==0，hhhh
<a href="https://imgtu.com/i/HOB0pt"><img src="https://s4.ax1x.com/2022/02/20/HOB0pt.png" alt="HOB0pt.png" border="0" /></a>
