### ISSUE TITLE
无论音乐人的主创说任务是否完成，每次运行都会发一次主创说

### ISSUE THREAD

**Issue by NianBroken** [chen310/NeteaseCloudMusicTasks#4]
希望可以加一个任务是否完成的判断
目前即便主创说任务已完成
在运行时，依旧会再发一次主创说

**Comment by chen310** [comment]
> 希望可以加一个任务是否完成的判断 目前即便主创说任务已完成 在运行时，依旧会再发一次主创说

回复粉丝评论引起的
