### ISSUE TITLE
测试失败，日志代码如下，感谢！

### ISSUE THREAD

**Issue by clownwait** [chen310/NeteaseCloudMusicTasks#44]
START RequestId: 5f758513-f16a-4a43-8869-e3594cd96193

Init Report RequestId: 5f758513-f16a-4a43-8869-e3594cd96193 Coldstart: 871ms (PullCode: 90ms InitRuntime: 8ms InitFunction: 773ms) Memory: 128MB MemUsage: 16.16MB

ERROR RequestId: 5f758513-f16a-4a43-8869-e3594cd96193 Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/index.py", line 6, in <module>     import json5 ModuleNotFoundError: No module named 'json5'", "statusCode": 443}

END RequestId: 5f758513-f16a-4a43-8869-e3594cd96193

Report RequestId: 5f758513-f16a-4a43-8869-e3594cd96193 Duration: 0ms Memory: 128MB MemUsage: 16.16MB

START RequestId:5f758513-f16a-4a43-8869-e3594cd96193

ERROR RequestId:5f758513-f16a-4a43-8869-e3594cd96193 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 6, in \u003cmodule\u003e\n    import json5\nModuleNotFoundError: No module named 'json5'","statusCode":443}

END RequestId:5f758513-f16a-4a43-8869-e3594cd96193

Report RequestId:5f758513-f16a-4a43-8869-e3594cd96193 Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by chen310** [comment]
#28
