### ISSUE TITLE
docker 部署每天只执行一次么？

### ISSUE THREAD

**Issue by xiaotianwl** [chen310/NeteaseCloudMusicTasks#50]
docker 部署每天只执行一次么？   如何每天多执行几次？
#### 打卡信息
- 本次打卡数: 9首
 播放次数有点少呀

**Comment by chen310** [comment]
@Chasing66

**Comment by xiaotianwl** [comment]
> @Chasing66

还是说 每天0点就开始执行  一直执行到播放290首就停止了？

**Comment by Chasing66** [comment]
docker 部署方式只是相当于创建了一个满足所需依赖的独立环境，增加了一个定时执行的功能，去调用**主函数**，其他部分与其他各种方式保持一致
1. 如果不指定时间，就先执行主函数一次，然后以后就定时执行，
2. 如果指定时间，仍然是先执行主函数一次， 再按照定时执行。

**Comment by xiaotianwl** [comment]
> docker 独立的方式只是相当于创建了一个满足依赖的环境，增加了一个主执行方式的功能，去调用部署**函数**，其他部分与其他各种保持一致
> 
> 1. 如果不指定时间，就先执行一次主函数，然后再定时执行，
> 2. 如果指定时间，仍然是先执行主函数一次，再按照定时执行。

每次定时任务打卡数量好少  
本次打卡数: 53首
我每次都是把docker 重启一次  打卡数量加一点点
本次打卡数: 12首
也就每天手动多重启几次   有点麻烦

**Comment by xiaotianwl** [comment]
> docker 增加独立的方式只是创建了一个满足依赖的环境，有一个主要的执行方式的功能，去部署部署**函数**，其他部分与其他各种保持一致
> 
> 1. 如果不指定时间，就先执行一次主要任务，然后再定时执行，
> 2. 如果时间，仍然是先执行主函数指定一次，再按照定时执行。

每次定时任务打卡数量好少
本次打卡数量：53首
我每次都是docker打重启打卡数量加点
本次打卡数量：12首
每天手动重启docker   有点麻烦

**Comment by chen310** [comment]
> > docker 独立的方式只是相当于创建了一个满足依赖的环境，增加了一个主执行方式的功能，去调用部署**函数**，其他部分与其他各种保持一致
> > 
> > 1. 如果不指定时间，就先执行一次主函数，然后再定时执行，
> > 2. 如果指定时间，仍然是先执行主函数一次，再按照定时执行。
> 
> 每次定时任务打卡数量好少  
> 本次打卡数: 53首
> 我每次都是把docker 重启一次  打卡数量加一点点
> 本次打卡数: 12首
> 也就每天手动多重启几次   有点麻烦
> 

换用云函数部署吧，成功的数量会高一些

**Comment by xiaotianwl** [comment]
> > > docker 增加独立的方式只是创建了一个满足依赖的环境，有一个主要的执行方式的功能，去部署部署**函数**，其他部分与其他各种保持一致
> > > 
> > > 1. 如果不指定时间，就先执行一次主要任务，然后再定时执行，
> > > 2. 如果时间，仍然是先执行主函数指定一次，再按照定时执行。
> > 
> > 
> > 每次定时任务打卡数量好少本次打卡数量
> > ：53首
> > 我每次都是docker打重启打卡数量加点打卡数量
> > ：12首
> > 每天手动多次重打多少次
> 
> 换用云作业部署吧，成功的人数会高一些

哦哦

**Comment by Chasing66** [comment]
> 

你通过进入到docker里面测试一下：
```shell
docker exec -it netease-cloud-music-tasks sh
python index.py
```
这种方法与[本地运行](https://github.com/chen310/NeteaseCloudMusicTasks#%E4%B8%89%E6%9C%AC%E5%9C%B0%E8%BF%90%E8%A1%8C)，完全一致，如果有问题，就是原函数的问题了
