### ISSUE TITLE
回复粉丝评论和私信，都是需要5次，跑一遍就回复1次

### ISSUE THREAD

**Issue by wdy3334** [chen310/NeteaseCloudMusicTasks#51]
首先谢谢大佬的工具

每日任务，回复粉丝评论和私信，都是需要5次，跑一遍就回复一次，每天跑5遍吗

还是谢谢大佬的工具

**Comment by chen310** [comment]
这其实是周任务，所以每天一次就行，一周内肯定能完成

**Comment by wdy3334** [comment]
> 这其实是周任务，所以每天一次就行，一周内肯定能完成

好的 我看它在每日任务里，以为每天做一遍呢，谢谢大佬
