### ISSUE TITLE
user.py文件中360行listenSongs时常会报KeyError的错误

### ISSUE THREAD

**Issue by nenniuwufang** [chen310/NeteaseCloudMusicTasks#53]
在我git clone整个git仓库到本地并且已经连接外网的情况下，时常会程序会出现变量listenSongs的KeyError的情况，这种错误的出现是概率性的，每一次运行后不一定会出现。
操作系统：Ubuntu20.04.3 LTS (GNU/Linux 5.4.0-1052-raspi aarch64)
硬件：树莓派4b 2GB ROM
python版本：Pyhton3.8.10

**Comment by chen310** [comment]
目测是网络问题

**Comment by nenniuwufang** [comment]
> 目测是网络问题

已经成功解决 确实是网络问题 感谢大佬🙏
