### ISSUE TITLE
云函数（hk）telegram推送失败

### ISSUE THREAD

**Issue by pcdgck** [chen310/NeteaseCloudMusicTasks#60]
![屏幕截图 2022-02-25 175734](https://user-images.githubusercontent.com/48538330/155695119-b3bd5157-4ffc-4c14-b267-b329c25cc8f6.png)

![屏幕截图 2022-02-25 175314](https://user-images.githubusercontent.com/48538330/155694603-fb5e3a80-6091-426b-a4a5-1e497e91a3b4.png)

**Comment by FlechazoPh** [comment]
同一个问题，是不是推送内容里的 ( 括号字符没有转义？ @chen310
