### ISSUE TITLE
Telegram 推送报错，疑似推送内容没有转义

### ISSUE THREAD

**Issue by FlechazoPh** [chen310/NeteaseCloudMusicTasks#61]
是不是推送内容某些格式和字符正则匹配 转义失败了？
![image](https://user-images.githubusercontent.com/94276146/155836853-fd4d60d0-f61a-4b4d-aba9-2955bd23186b.png)

**Comment by FlechazoPh** [comment]
希望能增加钉钉推送，接入API也挺简单的

**Comment by Gudark** [comment]
同Telegram推送失败，提示443，自己在网页链接测试机器人无问题，请问是反代失效了吗
