### ISSUE TITLE
最近打卡正常，但是升级剩余天数却没有变化

### ISSUE THREAD

**Issue by sinner7620** [chen310/NeteaseCloudMusicTasks#62]
![image](https://user-images.githubusercontent.com/62606659/155843604-84c07ee4-227e-4080-86f8-a4e5eace8028.png)
![image](https://user-images.githubusercontent.com/62606659/155843635-b2e3ee3f-1cb6-4602-b065-2ba21c86b91f.png)
如图剩余天数一直都没变化

**Comment by chen310** [comment]
天数随缘，没法保证一定增加

**Comment by sinner7620** [comment]
可是我就只差这个升级天数了😂

**Comment by chen310** [comment]
通过使用网易云app来增加天数吧
