### ISSUE TITLE
云豆任务大改

### ISSUE THREAD

**Issue by Chjne** [chen310/NeteaseCloudMusicTasks#64]
最新版网易云任务方式进行了变更

**Comment by chen310** [comment]
详细说说

**Comment by Chjne** [comment]
> 详细说说

![Screenshot_2022_0228_091845](https://user-images.githubusercontent.com/100081104/155909422-d77d7427-63b9-4a1d-afae-a2b91b748a0c.jpg)
如图，加了一些之前没有的，而且之前有的有些放在了推荐任务里，导致无法自动完成，周任务里程没了，但是脚本里还能领

**Comment by chen310** [comment]
我更新了，你试试能不能用

**Comment by chen310** [comment]
看一下日志

**Comment by Chjne** [comment]
> 

![image](https://user-images.githubusercontent.com/100081104/155923321-fb6ad678-5e0b-4583-99b2-a9ebbfe42f37.png)

**Comment by chen310** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/100081104/155923321-fb6ad678-5e0b-4583-99b2-a9ebbfe42f37.png)
> 

已更新，再试试

**Comment by Chjne** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/100081104/155923321-fb6ad678-5e0b-4583-99b2-a9ebbfe42f37.png)
> 
> 已更新，再试试

![image](https://user-images.githubusercontent.com/100081104/155924897-58aa9371-5650-4743-88ed-215d9b074ade.png)
可以了，最后的代码我也不知道啥意思，刚登上看了一下能完成了，但是主创说的云豆没自动领，我手动领了

**Comment by chen310** [comment]
又更新了一下，可能还是存在问题

**Comment by Chjne** [comment]
> 又更新了一下，可能还是存在问题
![image](https://user-images.githubusercontent.com/100081104/155973365-e5d73a62-1252-470c-94b8-e86cf0d42adc.png)
不好意思下午去上课了，再看看吧楼主
另外我发现这里提示有问题
![image](https://user-images.githubusercontent.com/100081104/155973466-a647725d-ada2-49d4-8a90-b9c0f9ebd648.png)

**Comment by chen310** [comment]
这个提示不用管。现在有两种任务，推荐任务和每日任务，推荐任务暂时还抓不到领取云豆的接口，所以`发布主创说`和`观看课程`只能手动领取云豆

**Comment by Chjne** [comment]
> 这个提示不用管。现在有两种任务，推荐任务和每日任务，推荐任务暂时还抓不到领取云豆的接口，所以`发布主创说`和`观看课程`只能手动领取云豆

嗯嗯，楼主给力
冒昧问一下楼主是不是姓陈(｀・ω・´)

**Comment by chen310** [comment]
是的
