### ISSUE TITLE
回复粉丝评论完成不了

### ISSUE THREAD

**Issue by UMRQWQ** [chen310/NeteaseCloudMusicTasks#69]
我设置ture了不会做

**Comment by UMRQWQ** [comment]
https://music.163.com:443 "POST /weapi/nmusician/workbench/mission/stage/list HTTP/1.1" 200 1265

发布动态: `云豆已经领取过了`

回复粉丝评论: `未完成`

https://music.163.com:443 "POST /weapi/nmusician/workbench/mission/reward/obtain/new HTTP/1.1" 200 56

回复粉丝私信: `云豆+2`

**Comment by chen310** [comment]
暂未找到原因

**Comment by chen310** [comment]
确定填写的是自己歌曲的 ID 吗？

**Comment by UMRQWQ** [comment]
> 确定填写的是自己歌曲的 ID 吗？

已经好啦！不知道怎么回事！ 谢谢大佬啦
