### ISSUE TITLE
播放歌单错误

### ISSUE THREAD

**Issue by haohan-liu** [chen310/NeteaseCloudMusicTasks#71]
最后一个显示播放歌单错误
![4Q2HX{M@G %GXN51T7 QY~H](https://user-images.githubusercontent.com/100924728/156741303-2a13af72-77f7-4e9e-aaf2-ae9bac7e67f2.png)

**Comment by chen310** [comment]
请用最新代码，不要用别人重新打包的代码

**Comment by chen310** [comment]
你好像fork错了，你fork的是别人的，没法更新。

**Comment by haohan-liu** [comment]
> 

fork大概从哪里修改？

**Comment by chen310** [comment]
删掉原来的，然后重新从 https://github.com/chen310/NeteaseCloudMusicTasks fork

**Comment by haohan-liu** [comment]
> 删掉原来的，然后重新从 https://github.com/chen310/NeteaseCloudMusicTasks fork

这个好像被改了，把你那个改动了好多，完全找不到，我把原来的包给你看看,我就换了几个歌单的id，其他都没动
https://wwz.lanzouv.com/i0LOP01008xi

**Comment by chen310** [comment]
这些不用不用管，你用最新的就行了，重新 fork

**Comment by haohan-liu** [comment]
> 这些不用不用管，你用最新的就行了，重新 fork

好
