### ISSUE TITLE
老是测试失败，但是部署成功了

### ISSUE THREAD

**Issue by haohan-liu** [chen310/NeteaseCloudMusicTasks#73]
这种怎么解决？![批注 2022-03-04 213503](https://user-images.githubusercontent.com/100924728/156772857-584ee621-2cf6-4ffb-b73b-adf550c5dfaa.png)

**Comment by chen310** [comment]
没有绑定层 https://github.com/chen310/NeteaseCloudMusicTasks#%E6%B7%BB%E5%8A%A0%E4%BE%9D%E8%B5%96

**Comment by haohan-liu** [comment]
> 没有绑定层 https://github.com/chen310/NeteaseCloudMusicTasks#%E6%B7%BB%E5%8A%A0%E4%BE%9D%E8%B5%96

从新绑了一次还是不行
![Uploading 批注 2022-03-04 221917.png…]()

**Comment by chen310** [comment]
图看不到，依赖下载对了吗

**Comment by chen310** [comment]
文件取消分享了，你下载的是这个吗 https://chen10.lanzouo.com/igHXzxf8wjc

**Comment by haohan-liu** [comment]
> 文件取消分享了，你下载的是这个吗 https://chen10.lanzouo.com/igHXzxf8wjc

你看看https://wwz.lanzouv.com/i2gzl01071hc

**Comment by chen310** [comment]
不是这个

**Comment by haohan-liu** [comment]
> 不是这个

我重新下载你上面那个链接从新上传绑定层

**Comment by haohan-liu** [comment]
> > 不是这个
> 
> 我重新下载你上面那个链接从新上传绑定层

![11](https://user-images.githubusercontent.com/100924728/156799380-72086ecd-2734-43a7-9e52-84d86611d20e.png)
我这个为啥绑定层之后打开代码管理就是已经输入过的数据了
![111](https://user-images.githubusercontent.com/100924728/156799440-68f6cf89-9707-46a0-8a44-6fa0b7efe124.png)

**Comment by chen310** [comment]
你没有删掉重新fork呀，用的还是老代码。还有，不要直接把账号密码填在GitHub上

**Comment by haohan-liu** [comment]
> 

我重新搞，不填在GitHub填写到那？云函数哪里吗？

**Comment by chen310** [comment]
可以，你可以看这个 https://music-pi.vercel.app/daka/

**Comment by haohan-liu** [comment]
> 可以，你可以看这个 https://music-pi.vercel.app/daka/

好

**Comment by haohan-liu** [comment]
> 可以，你可以看这个 https://music-pi.vercel.app/daka/

就是教程里面有个有说设置两个触发器，第一个是默认时间，第二个是统计数量的时间，上面说的是写成10 0 0 * * * *这个触发时间，我可不可以换成0 3 10 * * *自定义的时间？还有就是假如要是更新新的版本是不是吧把的依赖从新上传到云函数，是删除从新上传新的还是直接上传他直接就替换了，保留一些我挂的账号信息
![11](https://user-images.githubusercontent.com/100924728/156818090-d9053adc-daee-4b48-a03b-30f6828856be.png)
![111](https://user-images.githubusercontent.com/100924728/156818101-7b7b4392-6daa-4418-8f75-2ae8406d5273.png)

**Comment by chen310** [comment]
10 0 0 * * * * 的最好不要改，可以改另一个。更新的话要下载新的代码包，然后上传，配置要重新填，依赖不用管。所以建议还是用GitHub部署，更新很方便

**Comment by haohan-liu** [comment]
> 10 0 0 * * * * 的最好不要改，可以改另一个。更新的话要下载新的代码包，然后上传，配置要重新填，依赖不用管。所以建议还是用GitHub部署，更新很方便

哦，好，我改回来，那个代码包一般都是从哪里下载呢？

**Comment by chen310** [comment]
从我给的链接里，不过我不一定会实时更新

**Comment by haohan-liu** [comment]
> 从我给的链接里，不过我不一定会实时更新

那个链接？我看一下日志，这个第二个触发器好像也能正常运行
![Uploading 屏幕截图 2022-03-05 100528.png…]()

**Comment by haohan-liu** [comment]
> 从我给的链接里，不过我不一定会实时更新

那个链接？我看一下日志，这个第二个触发器好像也能正常运行
![屏幕截图 2022-03-05 100528](https://user-images.githubusercontent.com/100924728/156863547-77dc7c3e-cce2-4562-a3c3-ddcc99444a03.png)

**Comment by chen310** [comment]
https://music-pi.vercel.app/daka/
没错啊，能正常运行。但是最好不要改时间，0点左右是最好的，时间偏的越多，获取到的信息可能就不准确了

**Comment by haohan-liu** [comment]
> https://music-pi.vercel.app/daka/ 没错啊，能正常运行。但是最好不要改时间，0点左右是最好的，时间偏的越多，获取到的信息可能就不准确了

哦，好

**Comment by haohan-liu** [comment]
> https://music-pi.vercel.app/daka/ 没错啊，能正常运行。但是最好不要改时间，0点左右是最好的，时间偏的越多，获取到的信息可能就不准确了

还有一个就是他里面有一个创主说说，是专门在歌曲下面评论的，但是这个只能是音乐人才能使用，才能去歌曲下面发布评论，那个改动哪里可以让普通用户下面评论的，但是这个只能是音乐人才能使用，才能去歌曲下面发布评论，那个改动哪里可以让普通用户也可以对歌曲进行评论呢也可以对歌曲进行评论呢
![创主](https://user-images.githubusercontent.com/100924728/156864327-fd46e6bd-d569-4ed2-9938-523d3e9c593a.jpg)
？

**Comment by chen310** [comment]
> > https://music-pi.vercel.app/daka/ 没错啊，能正常运行。但是最好不要改时间，0点左右是最好的，时间偏的越多，获取到的信息可能就不准确了
> 
> 还有一个就是他里面有一个创主说说，是专门在歌曲下面评论的，但是这个只能是音乐人才能使用，才能去歌曲下面发布评论，那个改动哪里可以让普通用户下面评论的，但是这个只能是音乐人才能使用，才能去歌曲下面发布评论，那个改动哪里可以让普通用户也可以对歌曲进行评论呢也可以对歌曲进行评论呢 ![创主](https://user-images.githubusercontent.com/100924728/156864327-fd46e6bd-d569-4ed2-9938-523d3e9c593a.jpg) ？

目前只有音乐人能用

**Comment by haohan-liu** [comment]
> > > https://music-pi.vercel.app/daka/ 没错啊，能正常运行。但是最好不要改时间，0点左右是最好的，时间偏的越多，获取到的信息可能就不准确了
> > 
> > 
> > 还有一个就是他里面有一个创主说说，是专门在歌曲下面评论的，但是这个只能是音乐人才能使用，才能去歌曲下面发布评论，那个改动哪里可以让普通用户下面评论的，但是这个只能是音乐人才能使用，才能去歌曲下面发布评论，那个改动哪里可以让普通用户也可以对歌曲进行评论呢也可以对歌曲进行评论呢 ![创主](https://user-images.githubusercontent.com/100924728/156864327-fd46e6bd-d569-4ed2-9938-523d3e9c593a.jpg) ？
> 
> 目前只有音乐人能用

就是没办法改一下让普通用户也可以运行这一条任务吗？

**Comment by chen310** [comment]
> > > > https://music-pi.vercel.app/daka/ 没错啊，能正常运行。但是最好不要改时间，0点左右是最好的，时间偏的越多，获取到的信息可能就不准确了
> > > 
> > > 
> > > 还有一个就是他里面有一个创主说说，是专门在歌曲下面评论的，但是这个只能是音乐人才能使用，才能去歌曲下面发布评论，那个改动哪里可以让普通用户下面评论的，但是这个只能是音乐人才能使用，才能去歌曲下面发布评论，那个改动哪里可以让普通用户也可以对歌曲进行评论呢也可以对歌曲进行评论呢 ![创主](https://user-images.githubusercontent.com/100924728/156864327-fd46e6bd-d569-4ed2-9938-523d3e9c593a.jpg) ？
> > 
> > 
> > 目前只有音乐人能用
> 
> 就是没办法改一下让普通用户也可以运行这一条任务吗？

目前没有这个打算

**Comment by haohan-liu** [comment]
哦，好的，谢谢。我可以转发你这个帖子吗？编辑好之后会在文章下面留下出处 保留你的版权

**Comment by chen310** [comment]
可以

**Comment by haohan-liu** [comment]
> 可以

好的

**Comment by haohan-liu** [comment]
> 可以

我又上传了一次遇到了这种情况怎么办？
![TI4RNE{}MC~0(EM%{B@Z5~7](https://user-images.githubusercontent.com/100924728/156873661-8ebea242-92ca-4766-9be9-c7e68b11aafc.png)
