### ISSUE TITLE
打卡数时不时为0

### ISSUE THREAD

**Issue by hongzhengli** [chen310/NeteaseCloudMusicTasks#74]
我用docker部署的服务，目前在用脚本重启docker 来达到多次打卡，但经常听歌数为0

**Comment by hongzhengli** [comment]
环境变量 SONG_NUMBER 不存在。项目地址: https://github.com/chen310/NeteaseCloudMusicTasks
已通过 cookie 登录
**用户信息**

        用户名称: `xxx`
        用户ID: `xxx`
        用户等级: `8`
        用户村龄: `1077天`
        云贝数量: `734`
        粉丝数量: `1`
        听歌总数: `3627`
        歌单数: `8`
        歌单总收藏数: `0`
        距离下级还需播放: `4373首歌`
        距离下级还需登录: `27天`

**签到信息**

        重复签到: `今天签到共获取5云贝`

**云贝任务**

        无可执行的任务

**领取云贝**

        无可领取的云贝

**打卡信息**

        本次打卡数: `0首`
        听歌总数: `3627首`
        温馨提示: 数据更新可能有延时，[点击查看最新数据](https://music.163.com/#/user/home?id=1802222102)

Scheduler hour: 0, minute: 10

**Comment by chen310** [comment]
建议部署到云函数，理论上讲，云函数部署的方式，刷的会更多一些

**Comment by hongzhengli** [comment]
> 建议部署到云函数，理论上讲，云函数部署的方式，刷的会更多一些

那定时执行任务的话，一天一般定几次

**Comment by chen310** [comment]
一般一次就差不多了，不行的话就两三次

**Comment by hongzhengli** [comment]
> 

那我去试一下，之前看到能docker，就去部署了，然后发现一天下来，经常就一次能打到卡QAQ，而且数量也不一定多

**Comment by hongzhengli** [comment]
> 建议部署到云函数，理论上讲，云函数部署的方式，刷的会更多一些

现在改为用云函数部署了，然后每天第一次打卡会说本次实际打卡1000+首，和有效打卡，这个是什么意思啊

【打卡信息】
  ➢ 本次实际打卡数: 1717首
  ➢ 今天有效打卡数: 20首
  ➢ 听歌总数: 4247首

**Comment by chen310** [comment]
关注 `今天有效打卡数` 就行了
