### ISSUE TITLE
又执行错误了楼主

### ISSUE THREAD

**Issue by Chjne** [chen310/NeteaseCloudMusicTasks#75]
哈哈，我又来麻烦你了楼主，今天一看直接一个任务也没完成

日志:

START RequestId:60526810-2b23-4b33-a17f-4ff954bbf325

Starting new HTTPS connection (1): music.163.com:443

https://music.163.com:443 "POST /weapi/user/level HTTP/1.1" 200 52

https://music.163.com:443 "POST /weapi/login/cellphone HTTP/1.1" 200 1227

已通过账号密码登录

https://music.163.com:443 "POST /weapi/v1/user/detail/529017269 HTTP/1.1" 200 1237

**用户信息**

用户名称: `Chjne`

用户ID: `529017269`

用户等级: `8`

用户村龄: `1710天`

https://music.163.com:443 "POST /weapi/music-vip-membership/client/vip/info HTTP/1.1" 200 67

ERROR RequestId:60526810-2b23-4b33-a17f-4ff954bbf325 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 154, in main_handler\n    start(event, context)\n  File \"/var/user/index.py\", line 77, in start\n    user.startTask()\n  File \"/var/user/user.py\", line 730, in startTask\n    self.userInfo()\n  File \"/var/user/user.py\", line 167, in userInfo\n    self.taskInfo('VIP等级', vip_resp['data']['redVipLevel'])\nKeyError: 'data'","statusCode":430}

END RequestId:60526810-2b23-4b33-a17f-4ff954bbf325

Report RequestId:60526810-2b23-4b33-a17f-4ff954bbf325 Duration:443ms Memory:128MB MemUsage:24.078125MB

**Comment by djs326** [comment]
![image](https://user-images.githubusercontent.com/61230480/156859400-f5ed78f0-5f69-456d-aeb8-4c3b25bb5ad1.png)

**Comment by chen310** [comment]
> ![image](https://user-images.githubusercontent.com/61230480/156859400-f5ed78f0-5f69-456d-aeb8-4c3b25bb5ad1.png)
> 

在浏览器上登录网易云，然后访问 http://music.163.com/api/user/level 看看返回的结果

**Comment by chen310** [comment]
> 哈哈，我又来麻烦你了楼主，今天一看直接一个任务也没完成
> 
> 日志:
> 
> START RequestId:60526810-2b23-4b33-a17f-4ff954bbf325
> 
> Starting new HTTPS connection (1): music.163.com:443
> 
> https://music.163.com:443 "POST /weapi/user/level HTTP/1.1" 200 52
> 
> https://music.163.com:443 "POST /weapi/login/cellphone HTTP/1.1" 200 1227
> 
> 已通过账号密码登录
> 
> https://music.163.com:443 "POST /weapi/v1/user/detail/529017269 HTTP/1.1" 200 1237
> 
> **用户信息**
> 
> 用户名称: `Chjne`
> 
> 用户ID: `529017269`
> 
> 用户等级: `8`
> 
> 用户村龄: `1710天`
> 
> https://music.163.com:443 "POST /weapi/music-vip-membership/client/vip/info HTTP/1.1" 200 67
> 
> ERROR RequestId:60526810-2b23-4b33-a17f-4ff954bbf325 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 154, in main_handler\n    start(event, context)\n  File \"/var/user/index.py\", line 77, in start\n    user.startTask()\n  File \"/var/user/user.py\", line 730, in startTask\n    self.userInfo()\n  File \"/var/user/user.py\", line 167, in userInfo\n    self.taskInfo('VIP等级', vip_resp['data']['redVipLevel'])\nKeyError: 'data'","statusCode":430}
> 
> END RequestId:60526810-2b23-4b33-a17f-4ff954bbf325
> 
> Report RequestId:60526810-2b23-4b33-a17f-4ff954bbf325 Duration:443ms Memory:128MB MemUsage:24.078125MB

这个账号有黑胶会员吗？

**Comment by Chjne** [comment]
> 

对滴对滴，昨天领了七天

**Comment by Chjne** [comment]
> > 哈哈，我又来麻烦你了楼主，今天一看直接一个任务也没完成
> > 日志:
> > START RequestId:60526810-2b23-4b33-a17f-4ff954bbf325
> > Starting new HTTPS connection (1): music.163.com:443
> > https://music.163.com:443 "POST /weapi/user/level HTTP/1.1" 200 52
> > https://music.163.com:443 "POST /weapi/login/cellphone HTTP/1.1" 200 1227
> > 已通过账号密码登录
> > https://music.163.com:443 "POST /weapi/v1/user/detail/529017269 HTTP/1.1" 200 1237
> > **用户信息**
> > 用户名称: `Chjne`
> > 用户ID: `529017269`
> > 用户等级: `8`
> > 用户村龄: `1710天`
> > https://music.163.com:443 "POST /weapi/music-vip-membership/client/vip/info HTTP/1.1" 200 67
> > ERROR RequestId:60526810-2b23-4b33-a17f-4ff954bbf325 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File "/var/user/index.py", line 154, in main_handler\n    start(event, context)\n  File "/var/user/index.py", line 77, in start\n    user.startTask()\n  File "/var/user/user.py", line 730, in startTask\n    self.userInfo()\n  File "/var/user/user.py", line 167, in userInfo\n    self.taskInfo('VIP等级', vip_resp['data']['redVipLevel'])\nKeyError: 'data'","statusCode":430}
> > END RequestId:60526810-2b23-4b33-a17f-4ff954bbf325
> > Report RequestId:60526810-2b23-4b33-a17f-4ff954bbf325 Duration:443ms Memory:128MB MemUsage:24.078125MB
> 
> 这个账号有黑胶会员吗？
对滴对滴，昨天领了七天

**Comment by chen310** [comment]
> > > 哈哈，我又来麻烦你了楼主，今天一看直接一个任务也没完成
> > > 日志:
> > > START RequestId:60526810-2b23-4b33-a17f-4ff954bbf325
> > > Starting new HTTPS connection (1): music.163.com:443
> > > https://music.163.com:443 "POST /weapi/user/level HTTP/1.1" 200 52
> > > https://music.163.com:443 "POST /weapi/login/cellphone HTTP/1.1" 200 1227
> > > 已通过账号密码登录
> > > https://music.163.com:443 "POST /weapi/v1/user/detail/529017269 HTTP/1.1" 200 1237
> > > **用户信息**
> > > 用户名称: `Chjne`
> > > 用户ID: `529017269`
> > > 用户等级: `8`
> > > 用户村龄: `1710天`
> > > https://music.163.com:443 "POST /weapi/music-vip-membership/client/vip/info HTTP/1.1" 200 67
> > > ERROR RequestId:60526810-2b23-4b33-a17f-4ff954bbf325 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File "/var/user/index.py", line 154, in main_handler\n    start(event, context)\n  File "/var/user/index.py", line 77, in start\n    user.startTask()\n  File "/var/user/user.py", line 730, in startTask\n    self.userInfo()\n  File "/var/user/user.py", line 167, in userInfo\n    self.taskInfo('VIP等级', vip_resp['data']['redVipLevel'])\nKeyError: 'data'","statusCode":430}
> > > END RequestId:60526810-2b23-4b33-a17f-4ff954bbf325
> > > Report RequestId:60526810-2b23-4b33-a17f-4ff954bbf325 Duration:443ms Memory:128MB MemUsage:24.078125MB
> > 
> > 这个账号有黑胶会员吗？
> 对滴对滴，昨天领了七天
> 

我更新了

**Comment by Chjne** [comment]
> 

![image](https://user-images.githubusercontent.com/100081104/156863654-ee4d88ef-fb4c-4ace-82b4-5b96be8947a8.png)
还是不行，楼主

**Comment by chen310** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/100081104/156863654-ee4d88ef-fb4c-4ace-82b4-5b96be8947a8.png) 还是不行，楼主

[http://music.163.com/api/user/level](http://music.163.com/api/user/level) 这个链接用网易云app私信发给随便一个人然后打开，看看返回的信息

**Comment by djs326** [comment]
> 

![image](https://user-images.githubusercontent.com/61230480/156868497-db4f8a52-b086-490f-b867-f016261c0bf7.png)

**Comment by chen310** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/61230480/156868497-db4f8a52-b086-490f-b867-f016261c0bf7.png)

删除云函数，重新部署试试

**Comment by djs326** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/61230480/156868497-db4f8a52-b086-490f-b867-f016261c0bf7.png)
> 
> 删除云函数，重新部署试试

好的

**Comment by djs326** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/61230480/156868497-db4f8a52-b086-490f-b867-f016261c0bf7.png)
> 
> 删除云函数，重新部署试试

好了，能用了
