### ISSUE TITLE
chen大救命啊报错了

### ISSUE THREAD

**Issue by SCmenghua** [chen310/NeteaseCloudMusicTasks#76]
直到今天凌晨0：30的这次自动执行还是没问题的，然后刚才我看见你更新了，我就同步了一下，然后去云函数测试了一下，结果报错

--------------------------------------

START RequestId: 96700ca2-8791-44cf-ad06-0a473e202107

START RequestId: 96700ca2-8791-44cf-ad06-0a473e202107

START RequestId: 96700ca2-8791-44cf-ad06-0a473e202107

START RequestId: 96700ca2-8791-44cf-ad06-0a473e202107

START RequestId: 96700ca2-8791-44cf-ad06-0a473e202107

START RequestId: 96700ca2-8791-44cf-ad06-0a473e202107

START RequestId: 96700ca2-8791-44cf-ad06-0a473e202107

START RequestId: 96700ca2-8791-44cf-ad06-0a473e202107

START RequestId: 96700ca2-8791-44cf-ad06-0a473e202107

START RequestId: 96700ca2-8791-44cf-ad06-0a473e202107

START RequestId: 96700ca2-8791-44cf-ad06-0a473e202107

START RequestId: 96700ca2-8791-44cf-ad06-0a473e202107

START RequestId: 96700ca2-8791-44cf-ad06-0a473e202107

Init Report RequestId: 96700ca2-8791-44cf-ad06-0a473e202107 Coldstart: 1738ms (PullCode: 313ms InitRuntime: 44ms InitFunction: 1381ms) Memory: 128MB MemUsage: 22.35MB

Starting new HTTPS connection (1): music.163.com:443

https://music.163.com:443 "POST /weapi/user/level HTTP/1.1" 200 52

https://music.163.com:443 "POST /weapi/login/cellphone HTTP/1.1" 200 1105

已通过账号密码登录

https://music.163.com:443 "POST /weapi/v1/user/detail/430212792 HTTP/1.1" 200 1078

**用户信息**

  用户名称: `遂成梦华`

  用户ID: `430212792`

  用户等级: `6`

  用户村龄: `1830天`

https://music.163.com:443 "POST /weapi/music-vip-membership/client/vip/info HTTP/1.1" 200 67

  云贝数量: `292`

https://music.163.com:443 "POST /weapi/usertool/yunbei/center/attention HTTP/1.1" 200 49

  粉丝数量: `28`

  听歌总数: `2475`

  歌单数: `2`

  歌单总收藏数: `0`

https://music.163.com:443 "POST /weapi/user/level HTTP/1.1" 200 52

获取用户等级失败:{'code': 301, 'message': None}

https://music.163.com:443 "POST /weapi/v1/user/detail/347837981 HTTP/1.1" 200 979

https://music.163.com:443 "POST /weapi/user/follow/347837981 HTTP/1.1" 200 52

**签到信息**

https://music.163.com:443 "POST /weapi/act/modules/signin/v2/progress HTTP/1.1" 200 119

签到进度获取失败 301:用户未登录

https://music.163.com:443 "POST /weapi/point/dailyTask HTTP/1.1" 200 52

  签到成功

**云贝任务**

https://music.163.com:443 "POST /weapi/usertool/task/list/all HTTP/1.1" 200 49

ERROR RequestId:96700ca2-8791-44cf-ad06-0a473e202107 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 154, in main_handler\n    start(event, context)\n  File \"/var/user/index.py\", line 77, in start\n    user.startTask()\n  File \"/var/user/user.py\", line 756, in startTask\n    self.yunbei_task()\n  File \"/var/user/user.py\", line 450, in yunbei_task\n    for t in resp['data']:\nKeyError: 'data'","statusCode":430}

END RequestId:96700ca2-8791-44cf-ad06-0a473e202107

Report RequestId:96700ca2-8791-44cf-ad06-0a473e202107 Duration:810ms Memory:128MB MemUsage:38.281387MB

---------------------------------------------

这是刚才测试输出的日志

**Comment by chen310** [comment]
我现在也很懵，不知道为什么，我自己没问题。

**Comment by SCmenghua** [comment]
我重新从第一步又弄了一遍，这次好了
