### ISSUE TITLE
青龙面板怎么配置config.json文件

### ISSUE THREAD

**Issue by HD12138** [chen310/NeteaseCloudMusicTasks#8]
在青龙面板,拉取成功后怎么对：配置文件 文件进行修改config.json，有大佬知道吗 本人小白谢谢！！

**Comment by chen310** [comment]
> 在青龙面板,拉取成功后怎么对：配置文件 文件进行修改config.json，有大佬知道吗 本人小白谢谢！！

看[文档](https://github.com/chen310/NeteaseCloudMusicTasks#%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE)
