### ISSUE TITLE
云函数报错了

### ISSUE THREAD

**Issue by Re1uy** [chen310/NeteaseCloudMusicTasks#80]
START RequestId: ce3f7332-6463-42ab-9988-f2d218730787

Init Report RequestId: ce3f7332-6463-42ab-9988-f2d218730787 Coldstart: 1040ms (PullCode: 157ms InitRuntime: 3ms InitFunction: 880ms) Memory: 128MB MemUsage: 25.22MB

Starting new HTTPS connection (1): music.163.com:443

https://music.163.com:443 "POST /weapi/user/level HTTP/1.1" 200 52

https://music.163.com:443 "POST /weapi/login/cellphone HTTP/1.1" 200 1130

已通过账号密码登录

https://music.163.com:443 "POST /weapi/v1/user/detail/430700469 HTTP/1.1" 200 976

**用户信息**

  用户名称: `-白濑玲-`

  用户ID: `430700469`

  用户等级: `10`

  用户村龄: `1831天`

https://music.163.com:443 "POST /weapi/music-vip-membership/client/vip/info HTTP/1.1" 200 67

  云贝数量: `2921`

https://music.163.com:443 "POST /weapi/usertool/yunbei/center/attention HTTP/1.1" 200 49

  粉丝数量: `12`

  听歌总数: `26911`

  歌单数: `9`

  歌单总收藏数: `7`

https://music.163.com:443 "POST /weapi/user/level HTTP/1.1" 200 52

获取用户等级失败:{'code': 301, 'message': None}

https://music.163.com:443 "POST /weapi/v1/user/detail/347837981 HTTP/1.1" 200 985

https://music.163.com:443 "POST /weapi/user/follow/347837981 HTTP/1.1" 200 52

**签到信息**

https://music.163.com:443 "POST /weapi/act/modules/signin/v2/progress HTTP/1.1" 200 119

签到进度获取失败 301:用户未登录

https://music.163.com:443 "POST /weapi/point/dailyTask HTTP/1.1" 200 52

  签到成功

**云贝任务**

https://music.163.com:443 "POST /weapi/usertool/task/list/all HTTP/1.1" 200 49

ERROR RequestId:ce3f7332-6463-42ab-9988-f2d218730787 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 154, in main_handler\n    start(event, context)\n  File \"/var/user/index.py\", line 77, in start\n    user.startTask()\n  File \"/var/user/user.py\", line 756, in startTask\n    self.yunbei_task()\n  File \"/var/user/user.py\", line 450, in yunbei_task\n    for t in resp['data']:\nKeyError: 'data'","statusCode":430}

END RequestId:ce3f7332-6463-42ab-9988-f2d218730787

Report RequestId:ce3f7332-6463-42ab-9988-f2d218730787 Duration:821ms Memory:128MB MemUsage:38.542969MB

**Comment by chen310** [comment]
wyy里私信你了
