### ISSUE TITLE
青龙拉不了库

### ISSUE THREAD

**Issue by Richard0914** [chen310/NeteaseCloudMusicTasks#84]
![Uploading Screenshot_2022-03-08-17-25-54-851_mark.via.png…]()
如图，依赖已安装，版本2.10.13

**Comment by Richard0914** [comment]
## 开始执行... 2022-03-08 17:25:22

python3: can't open file 'ql_update.py': [Errno 2] No such file or directory

## 执行结束... 2022-03-08 17:25:22 耗时 0 秒

**Comment by chen310** [comment]
图看不到
试一试 `ql repo https://github.com/chen310/NeteaseCloudMusicTasks.git "index.py" "" "py" && task chen310_NeteaseCloudMusicTasks/ql_update.py`

**Comment by Richard0914** [comment]
![Screenshot_2022-03-08-17-50-05-309_mark via](https://user-images.githubusercontent.com/62535375/157211766-0b8f767e-9403-41ee-8bd0-31a501893a7c.png)
还是不行

**Comment by Richard0914** [comment]
换代理解决了
