### ISSUE TITLE
732004 问题 

### ISSUE THREAD

**Issue by 957341482** [chen310/NeteaseCloudMusicTasks#86]
本地运行时：
Traceback (most recent call last):
  File "index.py", line 161, in <module>
    start()
  File "index.py", line 79, in start
    user.startTask()
  File "/root/NeteaseCloudMusicTasks/user.py", line 760, in startTask
    self.musician_task()
  File "/root/NeteaseCloudMusicTasks/user.py", line 585, in musician_task
    if tasks['732004']['delete'] and len(self.replies) > 0:
KeyError: '732004'

云函数运行时:
https://music.163.com:443 "POST /weapi/nmusician/workbench/mission/cycle/list HTTP/1.1" 200 1189

https://music.163.com:443 "POST /weapi/nmusician/workbench/mission/stage/list HTTP/1.1" 200 1282

ERROR RequestId:527f92a8-2ad2-46c4-a583-c147452faf12 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 156, in main_handler\n    start(event, context)\n  File \"/var/user/index.py\", line 79, in start\n    user.startTask()\n  File \"/var/user/user.py\", line 760, in startTask\n    self.musician_task()\n  File \"/var/user/user.py\", line 585, in musician_task\n    if tasks['732004']['delete'] and len(self.replies) \u003e 0:\nKeyError: '732004'","statusCode":430}

END RequestId:527f92a8-2ad2-46c4-a583-c147452faf12

Report RequestId:527f92a8-2ad2-46c4-a583-c147452faf12 Duration:7661ms Memory:128MB MemUsage:22.747475MB

**Comment by chen310** [comment]
配置文件有问题

**Comment by chen310** [comment]
回复粉丝评论这个任务的配置被删了？

**Comment by 957341482** [comment]
没有删除任务配置，只配置账号，其他都不动，也报错

**Comment by chen310** [comment]
配置文件里找到回复粉丝评论这个任务，截个图看看

**Comment by 957341482** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chen310/NeteaseCloudMusicTasks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月9日(星期三) 下午2:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chen310/NeteaseCloudMusicTasks] 732004 问题  (Issue #86)





 
配置文件里找到回复粉丝评论这个任务，截个图看看
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 957341482** [comment]
邮箱发过去了，收到没有

**Comment by chen310** [comment]
没有

**Comment by 957341482** [comment]
![微信截图_20220309141829](https://user-images.githubusercontent.com/48375547/157391387-ea9669e2-a8c0-4032-8c2b-8d3e476718e5.png)

**Comment by chen310** [comment]
你更新了代码，但配置文件没更新

**Comment by 957341482** [comment]
ok,已解决
