### ISSUE TITLE
青龙拉库指令是不是有问题

### ISSUE THREAD

**Issue by MeucoMei** [chen310/NeteaseCloudMusicTasks#9]
总是显示路径有问题啊
![JN5Y EX5F_XXPM(G~8}T$02](https://user-images.githubusercontent.com/56835946/147736638-92d9afea-9489-498b-b9a5-fd471f8d7697.png)

**Comment by chen310** [comment]
> 总是显示路径有问题啊
> ![JN5Y EX5F_XXPM(G~8}T$02](https://user-images.githubusercontent.com/56835946/147736638-92d9afea-9489-498b-b9a5-fd471f8d7697.png)
> 
> 

看看文件夹里都有哪些文件 `ls /ql/scripts/chen310_NeteaseCloudMusicTasks/`

**Comment by MeucoMei** [comment]
> 

 No such file or directory
这个文件夹都没创建出来 很奇怪
而且唯一生成的文件名是chen310_NeteaseCloudMusicTasks_index.py 在scripts里面

**Comment by chen310** [comment]
> > 
> 
>  No such file or directory
> 这个文件夹都没创建出来 很奇怪
> 而且唯一生成的文件名是chen310_NeteaseCloudMusicTasks_index.py 在scripts里面

不清楚，对青龙还是不太了解

**Comment by MeucoMei** [comment]
啊这。。 我觉得是不是不能放文件夹里面。。放文件夹里面获取不到 如果把NeteaseCloudMusicTasks/换成NeteaseCloudMusicTasks_可能有用？

**Comment by MeucoMei** [comment]
阿哲。。

**Comment by chen310** [comment]
> 阿哲。。

我使用了拉库命令后，就自动帮我创建了一个文件夹用来放脚本，我不清楚你那里为什么只有一个文件。难道和青龙版本有关？

**Comment by MeucoMei** [comment]
好家伙 还真是版本问题 更新就解决了。。

**Comment by panliang-rm** [comment]
> 

如何更新青龙版本
