### ISSUE TITLE
运行在本地的怎么更新 , git pull 没效果

### ISSUE THREAD

**Issue by 957341482** [chen310/NeteaseCloudMusicTasks#91]

**Comment by chen310** [comment]
已支持，需删除原先的代码，重新 `git clone`，之后即可使用 `git pull` 进行更新，详见 [本地部署](https://github.com/chen310/NeteaseCloudMusicTasks#%E4%B8%89%E6%9C%AC%E5%9C%B0%E8%BF%90%E8%A1%8C)
