### ISSUE TITLE
请问utils.py可以添加前缀吗？

### ISSUE THREAD

**Issue by fidcz** [chen310/NeteaseCloudMusicTasks#93]
在青龙老版本和其他签到面板同时拉取的时候，会替换其他库的utils.py文件或者被其他库的替换。我还拉了其他的签到面板，两个utils.py就一直在互相替换，导致会有一边的任务跑不起来....
[https://github.com/Oreomeow/checkinpanel](url) 现在拉的是这家的签到面板，也在他们那提issues了

**Comment by chen310** [comment]
你升级一下青龙版本吧
