### ISSUE TITLE
大佬，青龙面板这个依赖怎么装

### ISSUE THREAD

**Issue by lxsb11122** [chen310/NeteaseCloudMusicTasks#96]
![image](https://user-images.githubusercontent.com/75591458/158061329-aeb9ccbc-5b50-4bc8-88b8-0c168025592f.png)

**Comment by chen310** [comment]
```shell
apk add python3-dev gcc libc-dev
pip3 install pycryptodomex
```

**Comment by lxsb11122** [comment]
> ```shell
> 添加python3-dev GCC libc-dev npip 3安装pycrypdomex
> ```
青龙依赖安装失败，算了，反正我本地可以正常运行，谢谢大佬
