### ISSUE TITLE
云函数报错

### ISSUE THREAD

**Issue by ghost** [chen310/NeteaseCloudMusicTasks#98]
START RequestId: 9294dfdc-8ee4-4bbf-bfab-e427c60272c2

START RequestId: 9294dfdc-8ee4-4bbf-bfab-e427c60272c2

START RequestId: 9294dfdc-8ee4-4bbf-bfab-e427c60272c2

Init Report RequestId: 9294dfdc-8ee4-4bbf-bfab-e427c60272c2 Coldstart: 927ms (PullCode: 135ms InitRuntime: 10ms InitFunction: 782ms) Memory: 64MB MemUsage: 22.66MB

ERROR RequestId:9294dfdc-8ee4-4bbf-bfab-e427c60272c2 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 156, in main_handler\n    start(event, context)\n  File \"/var/user/index.py\", line 53, in start\n    with open('config.json', 'r', encoding='utf-8') as f:\nFileNotFoundError: [Errno 2] No such file or directory: 'config.json'","statusCode":430}

END RequestId:9294dfdc-8ee4-4bbf-bfab-e427c60272c2

Report RequestId:9294dfdc-8ee4-4bbf-bfab-e427c60272c2 Duration:1ms Memory:64MB MemUsage:39.832031MB

**Comment by mybdye** [comment]
检查下 config.json

**Comment by chen310** [comment]
找不到配置文件，你可以手动新建一个
