### ISSUE TITLE
mlog问题

### ISSUE THREAD

**Issue by QQjq** [chen310/NeteaseCloudMusicTasks#99]
➢ 发布mlog: 未开启任务
之前正常，开启多账户以后，无论是主配置setting还是单独的账号setting都显示没有开启任务，不知道什么原因导致，需要提供怎样的日志？

**Comment by chen310** [comment]
到 `config.json` 文件的音乐人任务中 重新配置 mlog任务

**Comment by QQjq** [comment]
尝试了改false，运行一遍再改成true，只留下一个id，还是未开启

**Comment by chen310** [comment]
你确定是在 `musician_task` 而不是 `yunbei_task` 中修改的吗

**Comment by QQjq** [comment]
我晕，原来有两个mlog配置，下面音乐人的没开，耽误时间了
